Added support for file upload and export configuration
vmware/alb-sdk pull request #1102
Opened 2020-02-27 12:43 UTC by AshwiniBodke

Done some modifications in AviApi and few test cases

Input json file

Refactored code for naming conventions and best practices.

Added support for file upload and export configuration

Done some modifications in AviApi and few test cases

Refactored code for naming conventions and best practices.

Added few changes for travis.yml

code changes made to make download file functionality generic.

Added support for file upload and export configuration

Done some modifications in AviApi and few test cases

Refactored code for naming conventions and best practices.

Added support for file upload and export configuration

Done some modifications in AviApi and few test cases

Refactored code for naming conventions and best practices.

code changes made to make download file functionality generic.

code refactired for file download

multipart file download support added & additional test cases written for the same

null check added for file downloa

added readme.md and latest jar into the target

added readme.md and latest jar into the target

Did some modifications in test cases

2020-02-27 13:53 UTC, chaitanyaavi commented on java/test/com/vmware/avi/sdk/MockAviSDKTest.java
> +		} catch (AviApiException | NullPointerException e) {
Null pointer should not be handled in catch put null check instead.

2020-02-27 13:59 UTC, chaitanyaavi commented
Change version in pom.xml to 18.2.8

2020-02-27 14:04 UTC, chaitanyaavi requested changes
Please update version and null check changes.

2020-02-27 14:25 UTC, AshwiniBodke commented on java/test/com/vmware/avi/sdk/MockAviSDKTest.java
> +		} catch (AviApiException | NullPointerException e) {
Removed.

2020-02-28 13:42 UTC, chaitanyaavi approved these changes

2020-03-06 14:48 UTC, grastogi23 approved these changes

2020-03-06 14:48 UTC, merged