AV-70462 Added change to wait for the controller ready state
vmware/alb-sdk pull request #1103
Opened 2020-03-03 12:19 UTC by yograjshisode

2020-03-04 04:39 UTC, grastogi23 requested changes
please add a unit test for the timeout.

2020-03-04 04:39 UTC, grastogi23 commented on go/session/avisession.go
> +			check, err := avisess.CheckControllerStatus()
should refactor to better Go standards.

2020-03-06 14:56 UTC, grastogi23 requested changes

2020-03-06 14:56 UTC, grastogi23 commented on go/session/avisession.go
> +			check, err := avisess.CheckControllerStatus()
if strings.Contains(err.Error(), "connection refused") {
	if check, err := avisess.CheckControllerStatus(); err == nil && check {
        	if uri == "login" {
			avisess.initiateSession()
		} else {
			return avisess.restRequest(verb, uri, payload, tenant, errorResult, retry+1)
		}
       } else {
          return nil, err;
       }

2020-03-09 20:55 UTC, grastogi23 requested changes

2020-03-09 20:55 UTC, grastogi23 commented on go/examples/test/aviclient_test.go
> +		fmt.Println("Didn't got the error for invalid controller IP.")
change got to "get"

2020-03-09 20:55 UTC, grastogi23 commented on go/session/avisession.go
> +					avisess.initiateSession()
This is not correct. should this be return? I don't think tests are exercising this part of the code.

2020-03-11 12:08 UTC, yograjshisode commented on go/session/avisession.go
> +					avisess.initiateSession()
Added fix for the return. Also verified the test case and found that controller with invalid IP not hitting the this part of code. We have also added the test case for terraform playbook in avi-dev which will help us to test this part of code. It's hard to reproduce the scenario for connection refuse once the controller is in up state. I have tried different ways like reboot warm and clean using API, disabled the avi_portal service, reboot VM(having issue with IP allocation)

2020-03-11 23:24 UTC, grastogi23 requested changes

2020-03-11 23:24 UTC, grastogi23 commented on go/examples/test/aviclient_test.go
> +	}
we should also add test for the case that initiate session works. 

1. create session with a new password that is not yet set on controller. This should fail
2. now update the password using another session to the new password
3. try the API with the correct password again. there should be no error.

2020-03-13 03:48 UTC, grastogi23 commented on go/session/avisession.go
> +		// Wait untill controller is in ready state
if err = nil {
glog.Infof("Req for uri %v RespCode %v", url, resp.StatusCode)
	errorResult.HttpStatusCode = resp.StatusCode
	avisess.collectCookiesFromResp(resp)
} else if ("connection refused") {
reetry
} else {
errorResult.err = fmt.Errorf("client.Do uri %v failed: %v", uri, err)
		dump, err := httputil.DumpRequestOut(req, true)
		debug(dump, err)
		return result, errorResult
}

2020-03-17 14:36 UTC, grastogi23 approved these changes

2020-03-17 14:36 UTC, merged