ProxyRestRequest to return http.Response
vmware/alb-sdk pull request #1141
Opened 2020-04-28 09:40 UTC by shubhamavi

2020-04-29 17:46 UTC, grastogi23 requested changes

2020-04-29 17:46 UTC, grastogi23 commented on go/session/avisession.go
> +func (avisess *AviSession) ProxyRestRequest(verb string, uri string, payload interface{}, tenant string, lastError error, retryNum ...int) (*http.Response, error) {
There are lot of code duplication. Can you please explore if we can merge the two. Also, do we need to create a multi-part variant as well? I can't remember why we needed this. can you please add it to the descriiptioin of the functiion

2020-04-29 18:30 UTC, chauhanshubham commented on go/session/avisession.go
> +func (avisess *AviSession) ProxyRestRequest(verb string, uri string, payload interface{}, tenant string, lastError error, retryNum ...int) (*http.Response, error) {
updated the PR comment

2020-05-07 14:24 UTC, grastogi23 approved these changes

2020-05-07 19:22 UTC, avi-ashutosh commented
Looks good to me, thanks for the enhancement @shubhamavi

2020-05-08 03:04 UTC, grastogi23 approved these changes

2020-05-08 03:04 UTC, merged