AV-86846  handle payload in post
vmware/alb-sdk pull request #1169
Opened 2020-06-05 05:08 UTC by manojkumarjain

AV-86846  handle payload in post

2020-06-05 05:11 UTC, grastogi23 requested changes

2020-06-05 05:11 UTC, grastogi23 commented on go/session/avisession.go
> +        glog.Infof("MANOJ PostRaw: %v", payload)
please remove "Manoj" from the debug. Also, printing payload may be very expensive. Let us also add unit test for this. I am surprised this was not caught in the previous commit.

2020-06-05 05:14 UTC, manojkumarjain commented on go/session/avisession.go
> +        glog.Infof("MANOJ PostRaw: %v", payload)
Will do after testing on ctrl

2020-06-05 05:16 UTC, grastogi23 commented on go/session/avisession.go
> +        glog.Infof("MANOJ PostRaw: %v", payload)
let us may be create a jira for sandeep or sdk to add support for PutRaw as well. I checked that is not supported.

2020-06-05 05:23 UTC, chauhanshubham commented on go/session/avisession.go
>  	resp, rerror := avisess.restRequest("POST", uri, nil, "", nil)
I think replacing nil with payload here is the only thing required. Newline at L954 needs to be replaced at L955

2020-06-05 05:43 UTC, shubhamavi commented on go/session/avisession.go
> +        glog.Infof("PostRaw: %v", payload)
not sure if we should log this, considering we are not logging the Post() payload as well. Maybe change it to Debug or remove it for consistency across other functions

2020-06-08 06:36 UTC, manojkumarjain commented on go/session/avisession.go
> +        glog.Infof("MANOJ PostRaw: %v", payload)
Sure Gaurav

2020-06-08 06:38 UTC, manojkumarjain commented
@grastogi23  please approve and merge.
Unit testing completed

2020-06-08 07:15 UTC, chauhanshubham approved these changes

2020-06-08 18:19 UTC, grastogi23 approved these changes

2020-06-08 18:19 UTC, merged