AV-88850: Provide more GO SDK client controls
vmware/alb-sdk pull request #1184
Opened 2020-06-30 07:37 UTC by mayank-avinetworks

2020-07-01 10:42 UTC, mayank-avinetworks commented on go/session/avisession.go
> +	return func(avisess *AviSession) error {
Shall we sanitise the input from user against +ve integer check?

2020-07-01 12:56 UTC, yograjshisode commented on go/session/avisession.go
> +func SetControllerStatusCheckLimits(numRetries, numIntervals int) func(*AviSession) error {
Can we add a argument to set the value of  infinitelyCheckCtrlStatus in function SetControllerStatusCheckLimits? It will help to easily switch between the infinitelyCheckCtrlStatus mode and newer one using the same session

2020-07-01 13:02 UTC, mayank-avinetworks commented on go/session/avisession.go
> +func SetControllerStatusCheckLimits(numRetries, numIntervals int) func(*AviSession) error {
@yograjshisode : I thought of few situations if we make that as configurable.
1. To maintain the backward compatibility we keep the same number of iterations and the sleep behaviour as it was earlier.
2. If we allow to change the mode in between the same session, then someone can change the configured retry/interval counts to sleep for exponentially increasing time on controller status check poll, which changes our behaviour the way it polls by sleeping exponentially longer time, today.

2020-07-01 13:39 UTC, manojkumarjain commented on go/session/avisession.go
> +func SetControllerStatusCheckLimits(numRetries, numIntervals int) func(*AviSession) error {
Looks fine to me.
Should we ask Sudipto  to pull SDK from this branch and test it

2020-07-01 13:50 UTC, manojkumarjain commented on go/session/avisession.go
> +	infinitelyCheckCtrlStatus bool
Please change variable name

2020-07-01 13:50 UTC, manojkumarjain commented on go/session/avisession.go
> +	// Number of retries the SDK should attempt when controller is not reachable.
The comments seems to be incorrect, CRL  should be reachable 
Also change var name 
ctrlStatusCheckRetryCount --> retryCount 
ctrlStatusCheckRetryInterval --> retryInterval

2020-07-01 13:50 UTC, manojkumarjain commented on go/session/avisession.go
> +	avisess.infinitelyCheckCtrlStatus = true
infinitelyCheckCtrlStatus --> isReachable or something similar

2020-07-01 13:50 UTC, manojkumarjain commented on go/session/avisession.go
> +func SetControllerStatusCheckLimits(numRetries, numIntervals int) func(*AviSession) error {
I agree, let us keep it backward compatible, if options are not set

2020-07-01 13:50 UTC, manojkumarjain commented on go/session/avisession.go
> +	return func(avisess *AviSession) error {
Yes all user supplied should be sanitize

2020-07-01 13:50 UTC, manojkumarjain commented on go/session/avisession.go
> +		avisess.infinitelyCheckCtrlStatus = false
Do we need this infinitelyCheckCtrlStatus?

2020-07-01 13:50 UTC, manojkumarjain commented on go/session/avisession.go
> +	var isControllerUp bool
Initialize to false

2020-07-01 13:59 UTC, grastogi23 requested changes

2020-07-01 13:59 UTC, grastogi23 commented on go/session/avisession.go
> +	infinitelyCheckCtrlStatus bool
We don't need this flag. if ctrlStatusCheckRetryInterval is not set then it is exponential. else it is fixed status check retry interval.

2020-07-01 13:59 UTC, grastogi23 commented on go/session/avisession.go
> +	ctrlStatusCheckRetryCount int
we already have retry count "max_api_retries". let us re-use it. no need to introduce a new retry number.

2020-07-01 13:59 UTC, grastogi23 commented on go/session/avisession.go
> +	ctrlStatusCheckRetryInterval int
Even this one can't we simply use api_retry_interval flag? In fact rename it to the better GoStandards.

2020-07-01 13:59 UTC, grastogi23 commented on go/session/avisession.go
> +		if avisess.infinitelyCheckCtrlStatus {
we can simply make it adaptive that if retry interval is set it becomes static. If not then it is exponential. 

Also, I would like to cap it at something like 5 mins. There is no point in letting it grow for anything more than 5mins.

2020-07-01 14:59 UTC, mayank-avinetworks commented on go/session/avisession.go
> +	infinitelyCheckCtrlStatus bool
sure, we can get rid of this.

2020-07-01 15:09 UTC, mayank-avinetworks commented on go/session/avisession.go
> +	ctrlStatusCheckRetryInterval int
@grastogi23 : I see few issues using the existing variables `api_retry_interval` and `max_api_retries` for controller status check polling.
The existing variables are used for timeout and retry count of HTTP client which actually sends request to controller.
* Controller bring up/reboot/re-electoion can take up to couple of mins, which controller status poll request might need to poll for significantly greater time period than a normal HTTP request.
* If  a user configures these variables during session init by considering that this will poll controller status for around 10 times over the period of  5/10 mins then it will also retry the failed REST APIs to controller for same time intervals and iterations.
* This could be other way as well. If use configures  3 retries over 10 sec each. that might not be able to poll controller status properly.

please let me know what are you thoughts on this?

2020-07-01 15:10 UTC, mayank-avinetworks commented on go/session/avisession.go
> +	return func(avisess *AviSession) error {
sure, Manoj.

2020-07-01 15:10 UTC, mayank-avinetworks commented on go/session/avisession.go
> +		avisess.infinitelyCheckCtrlStatus = false
This was to override default value, but anyways, this flag is going away now :)

2020-07-01 15:11 UTC, mayank-avinetworks commented on go/session/avisession.go
> +	var isControllerUp bool
this will be initialised to false by itself .

2020-07-02 04:56 UTC, manojkumarjain commented on go/session/avisession.go
> +	var isControllerUp bool
isControllerUp := bool

2020-07-02 04:59 UTC, manojkumarjain commented on go/session/avisession.go
> +		if avisess.infinitelyCheckCtrlStatus {
Good point, let cap it to max 5 mins in case of exponential

2020-07-02 07:00 UTC, mayank-avinetworks commented on go/session/avisession.go
> +	var isControllerUp bool
go runtime initialises the bool to false by default.

2020-07-02 11:35 UTC, manojkumarjain approved these changes
Approve

2020-07-02 20:51 UTC, grastogi23 requested changes

2020-07-02 20:51 UTC, grastogi23 commented on go/session/avisession.go
> +	ctrlStatusCheckRetryInterval int
Sure. makes sense... let us keep them separate.

2020-07-02 20:51 UTC, grastogi23 commented on go/session/avisession.go
> +			time.Sleep(time.Duration(30) * time.Second)
min (time.Sleep(time.Duration(math.Exp(float64(round))*3) * time.Second), time.Sleep(time.Duration(30) * time.Second))

2020-07-03 03:14 UTC, mayank-avinetworks commented on go/session/avisession.go
> +			time.Sleep(time.Duration(30) * time.Second)
Done. 👍

2020-07-03 04:22 UTC, grastogi23 approved these changes

2020-07-03 04:22 UTC, merged