Add support for cloning GSLB Services
vmware/alb-sdk pull request #1240
Opened 2020-08-27 16:50 UTC by thebertster

2020-08-27 19:03 UTC, grastogi23 requested changes

2020-08-27 19:03 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
> +            elif args.obj_type == 'gs':
can we split this into its own method/function so it gets own importance ;)

2020-08-27 19:03 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
> +                        raise Exception('Number of FQDNs '
good to print out the fqdns and the value that were not consistent.

2020-08-27 19:03 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
> +                    all_created_objs.extend(cloned_objs)
what happens to the GSLB Pool members? those don't seem to be cloned? would that not cause problem if done on the same controller?

2020-08-27 19:07 UTC, thebertster commented on python/avi/sdk/samples/clone_vs.py
> +            elif args.obj_type == 'gs':
GSLB cloning is in its own method already (clone_gs).

2020-08-27 19:15 UTC, thebertster commented on python/avi/sdk/samples/clone_vs.py
> +                    all_created_objs.extend(cloned_objs)
Well unlike a normal VS that has pools as referred objects, a GSLB VS just holds references to site and VS UUIDs within itself, so there are no child objects to clone.

It would be nice to have an option to recursively clone the pool member VSs too as that could be a use case, but that would only make sense if we would also clone the pool members on the remote sites' Controllers too which will get increasingly complex.

One option I will likely implement is a mapping table to allow the user to map from a source VS UUID to a destination VS UUID as a pool member - this wouldn't need any direct interaction with the remote sites' Controllers, but the user would have to supply the source/destination UUIDs...not sure how important this use case is.

2020-08-27 19:15 UTC, thebertster commented on python/avi/sdk/samples/clone_vs.py
> +                        raise Exception('Number of FQDNs '
Yes, I will add this and also for the similar message for the clone_vs function.

2020-08-27 19:48 UTC, thebertster commented on python/avi/sdk/samples/clone_vs.py
> +                        raise Exception('Number of FQDNs '
Done.

2020-08-27 19:49 UTC, thebertster commented on python/avi/sdk/samples/clone_vs.py
> +                    all_created_objs.extend(cloned_objs)
For now, this use case seems to meet the needs of the customer that requested it, so can we please push this change and then look at a further enhancement in future?

2020-08-28 20:46 UTC, grastogi23 approved these changes

2020-08-28 20:46 UTC, merged