#AV-64697 Added example to use with SDk with new Patch Syntax
vmware/alb-sdk pull request #1257
Opened 2020-10-23 11:47 UTC by shounak-opcito

Added examples for the following operations using latest Patch api. (One  can find the example function in file patch_api_example.py):
- add new server to existing pool (add_server_to_pool())
- remove server from a pool (remove_server_from_pool())
- update server in existing pool (update_server_in_pool())

2020-10-23 15:18 UTC, grastogi23 requested changes

2020-10-23 15:18 UTC, grastogi23 commented on python/avi/sdk/samples/patch_api_example.py
> +    def get_server_obj(self, server):
Please document functions use 
https://avinetworks.atlassian.net/wiki/spaces/EN/pages/12917148/Coding+Guidelines

2020-10-23 15:18 UTC, grastogi23 commented on python/avi/sdk/samples/patch_api_example.py
> +                    lb_algorithm='LB_ALGORITHM_LEAST_CONNECTIONS'):
https://avinetworks.atlassian.net/wiki/spaces/EN/pages/12917148/Coding+Guidelines

2020-10-23 15:18 UTC, grastogi23 commented on python/avi/sdk/samples/patch_api_example.py
> +    def add_server_to_pool(self, server, pool_uuid):
https://avinetworks.atlassian.net/wiki/spaces/EN/pages/12917148/Coding+Guidelines

2020-10-23 15:18 UTC, grastogi23 commented on python/avi/sdk/samples/patch_api_example.py
> +if __name__ == "__main__":
Add examples section for this. Look at how f5 converters do it.

2020-10-26 13:23 UTC, shounak-opcito commented on python/avi/sdk/samples/patch_api_example.py
> +    def get_server_obj(self, server):
added required comment

2020-10-26 13:23 UTC, shounak-opcito commented on python/avi/sdk/samples/patch_api_example.py
> +                    lb_algorithm='LB_ALGORITHM_LEAST_CONNECTIONS'):
added required comment

2020-10-26 13:23 UTC, shounak-opcito commented on python/avi/sdk/samples/patch_api_example.py
> +    def add_server_to_pool(self, server, pool_uuid):
added required comment

2020-10-26 13:24 UTC, shounak-opcito commented on python/avi/sdk/samples/patch_api_example.py
> +if __name__ == "__main__":
Added example section

2020-11-05 15:32 UTC, grastogi23 approved these changes

2020-11-05 15:32 UTC, merged