Added config file parameter for migration script
vmware/alb-sdk pull request #1313
Opened 2021-01-12 12:12 UTC by shardullatkar

2021-01-15 11:49 UTC, chaitanyaavi commented
@shardullatkar This change is required in 20.1.4 please cherry pick to 20.1.4 branch

2021-01-15 12:02 UTC, chaitanyaavi requested changes

2021-01-15 12:02 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/f5_converter.py
> +                partitions = self.partition_config
this has to be list as split returns the list something like following
partitions = [self.partition_config]

2021-01-15 12:02 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/f5_converter.py
> +                        if terminal_args.__dict__[terminal_arg] is None and terminal_arg in ARG_DEFAULT_VALUE.keys():
both the if statements can be combined

2021-01-15 12:02 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/f5_converter.py
> +    # print("\n FINAL ARGS ============== %s" % terminal_args.__dict__)
Add logger statement here.

2021-01-15 12:02 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/f5_converter.py
> +        controller_version: '17.2.1'
Use version >18.2.x

2021-01-15 12:02 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/test/test_migrationtool.py
> +        output_file_path=output_file, option='cli-upload', user='admin',
Instead of hardcoding can we use it from ARG_DEFAULT_VALUE

2021-01-15 12:02 UTC, chaitanyaavi commented on python/avi/migrationtools/vs_filter.py
> +        virtual_services = vs_names
Need to be list

2021-01-15 12:03 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/config.yaml
> +# type: string
Remove 'type' from all options

2021-01-15 12:06 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/config.yaml
> +# description:
Put option name before description

2021-01-15 12:07 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/config.yaml
> +#   version: true
Version not required on config file this will be CLI only option

2021-01-15 12:08 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/config.yaml
> +#ansible: false
Example 
# Option: ansible
# description:
#   - Flag for creating ansible file
#   - It will convert json configuration into ansible and generate yaml file
#     to create and delete the configuration on the controller
# default: false
# choices: [true, false]
# example:
#   ansible: true

#ansible: false

2021-01-15 12:08 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/config.yaml
> +#ansible: false
Example
`# Option: ansible
# description:
#   - Flag for creating ansible file
#   - It will convert json configuration into ansible and generate yaml file
#     to create and delete the configuration on the controller
# default: false
# choices: [true, false]
# example:
#   ansible: true

#ansible: false`

2021-01-15 12:09 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/config.yaml
> +#ansible: false
`
# Option: ansible
# description:
#   - Flag for creating ansible file
#   - It will convert json configuration into ansible and generate yaml file
#     to create and delete the configuration on the controller
# default: false
# choices: [true, false]
# example:
#   ansible: true

#ansible: false
`

2021-01-15 12:09 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/config.yaml
> +#ansible: false
```suggestion
#ansible: false

# Option: ansible
# description:
#   - Flag for creating ansible file
#   - It will convert json configuration into ansible and generate yaml file
#     to create and delete the configuration on the controller
# default: false
# choices: [true, false]
# example:
#   ansible: true

#ansible: false
```

2021-01-15 12:11 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/config.yaml
> +# description:
Example block
```
# Option: ansible
# description:
#   - Flag for creating ansible file
#   - It will convert json configuration into ansible and generate yaml file
#     to create and delete the configuration on the controller
# default: false
# choices: [true, false]
# example:
#   ansible: true

#ansible: false
```

2021-01-15 18:41 UTC, shardullatkar commented on python/avi/migrationtools/f5_converter/config.yaml
> +# description:
Added

2021-01-15 18:42 UTC, shardullatkar commented on python/avi/migrationtools/f5_converter/config.yaml
> +# description:
Done for all arguments

2021-01-15 18:50 UTC, shardullatkar commented on python/avi/migrationtools/vs_filter.py
> +        virtual_services = vs_names
Realized that is handled in f5_convertor itself, but to rule out any error have added type check.

2021-01-15 18:54 UTC, shardullatkar commented on python/avi/migrationtools/f5_converter/config.yaml
> +#   version: true
Removed from config file

2021-01-15 18:55 UTC, shardullatkar commented on python/avi/migrationtools/f5_converter/f5_converter.py
> +                partitions = self.partition_config
Realized that is handled in f5_convertor itself, but to rule out any error have added type check.

2021-01-15 18:55 UTC, shardullatkar commented on python/avi/migrationtools/f5_converter/f5_converter.py
> +                        if terminal_args.__dict__[terminal_arg] is None and terminal_arg in ARG_DEFAULT_VALUE.keys():
Had kept is for readability purpose but have merged them now.

2021-01-15 18:55 UTC, shardullatkar commented on python/avi/migrationtools/f5_converter/f5_converter.py
> +    # print("\n FINAL ARGS ============== %s" % terminal_args.__dict__)
Added

2021-01-15 18:56 UTC, shardullatkar commented on python/avi/migrationtools/f5_converter/f5_converter.py
> +        controller_version: '17.2.1'
Kept it as current version 20.1.4

2021-01-15 18:56 UTC, shardullatkar commented on python/avi/migrationtools/f5_converter/test/test_migrationtool.py
> +        output_file_path=output_file, option='cli-upload', user='admin',
Used arg default dict value

2021-01-15 18:57 UTC, shardullatkar commented on python/avi/migrationtools/f5_converter/config.yaml
> +# type: string
Removed

2021-01-15 19:02 UTC, shardullatkar reviewed
Addressed comments

2021-01-18 08:39 UTC, chaitanyaavi approved these changes

2021-01-18 08:39 UTC, merged