#AV-102732: Java SDK release script changes
vmware/alb-sdk pull request #1353
Opened 2021-02-24 16:10 UTC by chaitanyaavi

2021-02-26 21:30 UTC, grastogi23 requested changes

2021-02-26 21:30 UTC, grastogi23 commented on create_release.sh
> +  echo "Cannot release java SDK environment is not set"
we should say that AVISDK_PGP_PASSPHRASE is not set. So anyone running it knows without looking at the code.

2021-02-26 21:40 UTC, grastogi23 commented on create_release.sh
>  /usr/local/bin/hub release $hub_op $assets -F ReleaseNote $REL_TAG
while we are at refactoring can we also check for output of the hub command and test for success. Only if the hub command is successful do rest of the following cleanups

2021-03-01 09:11 UTC, chaitanyaavi commented on create_release.sh
>  /usr/local/bin/hub release $hub_op $assets -F ReleaseNote $REL_TAG
Cleanups are harmless even if the release is not done removing will not error out

2021-03-08 19:39 UTC, grastogi23 approved these changes

2021-03-11 19:13 UTC, grastogi23 requested changes

2021-03-11 19:13 UTC, grastogi23 commented on create_release.sh
> +  echo "Cannot release java SDK environment is not set"
we should also exit from here. not just be in else.

2021-03-11 19:13 UTC, grastogi23 commented on create_release.sh
> +  echo "Cannot release java SDK AVISDK_PGP_PASSPHRASE is not set"
There should be an exit here. There is no reason to continue the release if the java cannot be released.

2021-03-23 09:45 UTC, manojkumarjain approved these changes
Approve

2021-03-23 09:47 UTC, merged