Rt 16.3 policy rules
vmware/alb-sdk pull request #136
Opened 2016-11-11 15:15 UTC by rameshtathe

I have made changes, Please review
1) Updated csvs_converter.py
2) Updated monitor_converter.py
3) Updated netscaler_parser.py
4) Updated netscaler_converter.py

2016-11-11 18:03 UTC, grastogi23 requested changes

2016-11-11 18:03 UTC, grastogi23 commented on .gitignore
> +.idea/
is this needed?

2016-11-11 18:03 UTC, grastogi23 commented on python/avi/netscaler_converter/csvs_converter.py
> +            matches = re.findall('\"(.+?)\"', query)
what if there are no matches?

2016-11-11 18:03 UTC, grastogi23 commented on python/avi/netscaler_converter/csvs_converter.py
> +        query = ns_rule.strip('"')
might be good to also remove the blank spaces.

2016-11-11 18:03 UTC, grastogi23 commented on python/avi/netscaler_converter/csvs_converter.py
> +            policy_obj["http_request_policy"]["rules"][0]["match"].update({"path": path_query})
can there not be a case that there are multiple rules in a single vs. this code may not work then?

2016-11-14 14:40 UTC, chaitanyaavi commented on .gitignore
> +.idea/
Yes. Its an pycharm files. We dont need to commit it.

2016-11-15 03:56 UTC, merged