Fixed hm count
vmware/alb-sdk pull request #144
Opened 2016-11-21 12:59 UTC by rameshtathe

I have made some changes, please review
1) Updated csvs_converter.py for HTTP.REQ.COOKIE.CONTAINS and equal rules.
2) Updated ns_service_converter.py of hm ref in pool for maximum count of HM

2016-11-21 13:12 UTC, chaitanyaavi requested changes

2016-11-21 13:12 UTC, chaitanyaavi commented on python/avi/netscaler_converter/ns_service_converter.py
> +        if len(monitors) == 1:
The logic should be generic it will fail for new supported attribute added check for duplicate policy remove logic in conversion_util.py of F5 converter for example.

2016-11-21 15:59 UTC, grastogi23 commented
Pl. also add test case for these changes.

2016-11-21 15:59 UTC, grastogi23 requested changes

2016-11-21 15:59 UTC, grastogi23 commented on python/avi/netscaler_converter/ns_service_converter.py
>                  pool_obj["health_monitor_refs"] = list(set(monitor_refs))
no need to do list(set(monitor_refs) as monitor_refs is already going to be a list.

2016-11-21 15:59 UTC, grastogi23 commented on python/avi/netscaler_converter/ns_service_converter.py
> +    def remove_duplicate_health_monitors(self, monitors):
add method documentation

2016-11-21 16:00 UTC, grastogi23 commented
Also, would like these fixes to be merged to 16.3 release branch as well.

2016-11-28 05:21 UTC, grastogi23 approved these changes

2016-11-28 05:22 UTC, grastogi23 commented
waiting on chaitanya to approve the request

2016-11-28 12:22 UTC, chaitanyaavi commented on python/avi/netscaler_converter/ns_service_converter.py
> +        if len(monitors) == 1:
t should make copy of object remove name and description from that and do dict comparison for duplicates
If we support any other attribute other than this condition in HM conversion this condition also need to be modified

2016-11-28 12:24 UTC, chaitanyaavi commented on python/avi/netscaler_converter/ns_service_converter.py
>                  pool_obj["health_monitor_refs"] = list(set(monitor_refs))
This is done to remove duplicates, set will remove the duplicates and for assigning to refs converted again to list

2016-11-28 15:45 UTC, chaitanyaavi approved these changes

2016-11-28 18:04 UTC, merged