Added test cases for remove duplicate health monitors
vmware/alb-sdk pull request #148
Opened 2016-11-24 03:27 UTC by rameshtathe

I have made changes, Please review
1) Updated test_ns_service_converter.cfg
2) test_ns_service_converter.py

2016-11-28 12:34 UTC, chaitanyaavi requested changes
I dont think we need this granular test cases for util methods add the scenario in the input data to cover this code and add assert for this condition.
@grastogi23 What are your thoughts on this?

2016-11-28 18:06 UTC, grastogi23 commented
I think it is good to have unit test case for the util methods. However, we should also add tests for covering some of the this code path in top level scenarios.

2016-11-28 20:48 UTC, grastogi23 requested changes

2016-11-28 20:48 UTC, grastogi23 commented on python/avi/netscaler_converter/test/test_ns_service_converter.py
> +    def remove_duplicate_health_monitors(self):
also, this is not a test... which code will call this function for testing?

2016-12-01 00:27 UTC, grastogi23 approved these changes

2016-12-01 20:25 UTC, merged