16.3 ns changes
vmware/alb-sdk pull request #161
Opened 2016-12-13 04:06 UTC by rameshtathe

2016-12-13 15:26 UTC, grastogi23 requested changes

2016-12-13 15:26 UTC, grastogi23 commented on python/avi/netscaler_converter/lbvs_converter.py
> +                if port == "0" or port == "*":
also write as if port in ("0", "*")

2016-12-13 15:26 UTC, grastogi23 commented on python/avi/netscaler_converter/ns_service_converter.py
> +
should the port range also be set to be 65535.

2016-12-13 15:26 UTC, grastogi23 commented on python/avi/netscaler_converter/ns_service_converter.py
> +            LOG.warning('Not found IP of server : %s' % ip_addr)
would it result in skip or just warning?

2016-12-13 15:26 UTC, grastogi23 commented on python/avi/netscaler_converter/ns_service_converter.py
> +                LOG.warning('Not found IP of server : %s' % ip_addr)
should say ignoring the server and print the full ns server object.

2016-12-13 15:26 UTC, grastogi23 commented on python/avi/netscaler_converter/ns_util.py
> +    for source_obj in obj_list:
this code needs re-write. If you are trying to find duplicates then simply put this in a hash and compare the objects or just put it in a set and then make list of out.

2016-12-14 17:09 UTC, rameshtathe commented on python/avi/netscaler_converter/ns_service_converter.py
> +
As we can see in VS proto, services has port_range_end but Servers does not have the port range in Pool proto
Please correct me if i am wrong

2016-12-14 17:16 UTC, rameshtathe commented on python/avi/netscaler_converter/ns_service_converter.py
> +            LOG.warning('Not found IP of server : %s' % ip_addr)
If you see, It return the list of servers. This function is call from get_servers and get servers called from convert. If it return the empty list then we skipped the bind lb vserver.

if not servers:
       ns_util.add_status_row(b_cmd, "Skipped")
       LOG.error('Error: No Servers found. Skipped pool : %s' % group_key)
       continue

2016-12-15 15:44 UTC, rameshtathe commented on python/avi/netscaler_converter/ns_util.py
> +    for source_obj in obj_list:
Fixed

2016-12-19 16:20 UTC, grastogi23 approved these changes

2016-12-19 16:20 UTC, grastogi23 commented on python/avi/netscaler_converter/ns_util.py
> +def remove_duplicate_server_objects(obj_type, obj_list):
can you also write a unit test for the duplicates.

2016-12-19 16:21 UTC, merged