New changes for Master
vmware/alb-sdk pull request #168
Opened 2017-01-02 11:09 UTC by rameshtathe

I have made following changes,

Log the build number for F5 and netscalar converter
Ignore more than 32 snat pools for F5 converter
Flag for ignoring default config for F5 converter
Support to convert _sys_https_redirect irule for F5 converter
Dummy datascript as placeholder for F5 Converter
Dummy ssl cert and key as placeholder for F5 converter

2017-01-02 15:21 UTC, grastogi23 requested changes

2017-01-02 15:21 UTC, grastogi23 commented on python/avi/f5_converter/f5_converter.py
> +from avi.version import AVI_VERSION, AVI_PIP_VERSION
this would require that we package version in the controller too. we need to check if that is happening

2017-01-02 15:21 UTC, grastogi23 commented on python/avi/f5_converter/f5_converter.py
> +        LOG.warning('Skipped default file : %s' % profile_base.name)
change message to "Could not find default file: %s. Skipping and using converter defaults"

2017-01-02 15:21 UTC, grastogi23 commented on python/avi/f5_converter/f5_converter.py
> +    parser.add_argument('--skip_default_file',
spelling. We don't need flag for this. it should be done automatically...

2017-01-02 15:21 UTC, grastogi23 commented on python/avi/f5_converter/f5_converter.py
> +    LOG.info('Avi Build version : %s' % AVI_VERSION)
Let us print this in the help string as well.

2017-01-02 15:21 UTC, grastogi23 commented on python/avi/f5_converter/vs_converter.py
> +        if 'rules' in f5_vs.keys():
check can just be if 'rules' in f5_vs

2017-01-02 15:21 UTC, grastogi23 commented on python/avi/f5_converter/vs_converter.py
> +            if len(snat_list):
let us re-write this logic.

If snat_list checks for len and is more efficient.
Print the logs when if len(snat_list) > 32 and log.

2017-01-02 15:21 UTC, grastogi23 commented on python/avi/f5_converter/vs_converter.py
> +        vs_ds_ref = rule + '-vs-datascript-dumy'
fix spelling dummy.

2017-01-04 06:39 UTC, chaitanyaavi requested changes

2017-01-04 06:39 UTC, chaitanyaavi commented on python/avi/f5_converter/f5_converter.py
> +        if not skip_default_file:
We need to have this check before parsing default config

2017-01-04 06:39 UTC, chaitanyaavi commented on python/avi/f5_converter/f5_converter.py
> +    parser.add_argument('--skip_default_file',
No As discussed on the call for quick fix we need this flag right?

2017-01-04 06:39 UTC, chaitanyaavi commented on python/avi/f5_converter/profile_converter.py
> +        if not generate_ssl_placeholder:
This should not be the flag driven, If the given cert file is not found on location then put the self cert and add warning in the log.

2017-01-09 21:04 UTC, closed without merging