Allow for callers to inject their own HTTP client
vmware/alb-sdk pull request #1750
Opened 2021-10-01 23:29 UTC by aaronjwood

Would be happy to discuss this more next week in our meeting with Manish.

2021-10-02 04:01 UTC, manojkumarjain commented
Isn't it injecting clientfactory will be better
It allow you to manage Session and httpclient with your scheme
In GoSDK we have given that features
Similar feature is develop in JavaSDK

2021-10-04 16:16 UTC, aaronjwood commented
> Isn't it injecting clientfactory will be better It allow you to manage Session and httpclient with your scheme In GoSDK we have given that features Similar feature is develop in JavaSDK

Sorry, I didn't quite follow you. I don't see a ClientFactory (or Factory) reference anywhere in the Go codebase.

2021-10-05 03:28 UTC, mayank-avinetworks commented
Hi @aaronjwood , We support setting custom transport and timeout while creating the avi session in GO SDK.
https://github.com/vmware/alb-sdk/blob/eng/go/examples/test/custom_transport_test.go#L143
I believe this example should solve your use case.

2021-10-05 16:05 UTC, aaronjwood commented
> Hi @aaronjwood , We support setting custom transport and timeout while creating the avi session in GO SDK.
> https://github.com/vmware/alb-sdk/blob/eng/go/examples/test/custom_transport_test.go#L143
> I believe this example should solve your use case.

The transport isn't enough to cover our use case. We can discuss why on the call later today.

2021-10-05 22:02 UTC, grastogi23 requested changes

2021-10-05 22:02 UTC, grastogi23 commented on go/session/avisession.go
> +	client HttpClient
It has been a while but there was a reason for using a ptr as some optimizations where being done by the core Go HTTP client module. Is there any reason why HTTPClient needs to be passed by value .

How about leave the client as *http.Client. But you can always set it in the  NewAviSession based on whether it was passed in the arguments list.

2021-10-05 22:02 UTC, grastogi23 commented on go/session/avisession.go
> +	if avisess.client == nil {
This code works as is. we don't need to make line 258 client HttpClient from client *HttpClient. It also avoids confusion whether the object's HTTPClient is used or one that was passed down.

2021-10-05 22:03 UTC, grastogi23 commented on go/session/avisession_test.go
> +func TestSetClient(t *testing.T) {
Thanks for adding this.

2021-10-05 22:05 UTC, grastogi23 commented on go/session/avisession.go
> +func SetClient(client HttpClient) func(*AviSession) error {
similar comment here. let it be (client *HttpClient) instead of pss by value

2021-10-05 22:36 UTC, aaronjwood commented on go/session/avisession.go
> +	client HttpClient
Interfaces are references underneath in Go which is why I kept it this way. I haven't seen people often taking pointers to interfaces unless you have some fancy stuff going on. It'd be a pointer to a pointer in that case.

I don't think I fully understood your comment about keeping it as a concrete struct type. If it's not an interface then passing it in `NewAviSession` will only allow for the standard lib `*http.Client` implementation to be used. We want to be able to swap the client out completely, not be restricted by it.

2021-10-05 22:37 UTC, aaronjwood commented on go/session/avisession.go
> +	if avisess.client == nil {
If the nil check is omitted then won't it overwrite the custom implementation being passed in? I think I saw the option parsing code above this area, so if you pass in `SetClient` in `NewAviSession` it'll be taken, but then here it'll just be overwritten if there's no guardrail.

2021-10-05 22:38 UTC, aaronjwood commented on go/session/avisession.go
> +func SetClient(client HttpClient) func(*AviSession) error {
Are you suggesting we move to using double pointers under the hood? The goal is to move away from a concrete struct type here so I'm relying on the implicit reference that the interface carries.

2021-10-06 03:52 UTC, grastogi23 commented on go/session/avisession.go
> +	client HttpClient
Hi
I have limited Go experience. But as far as I know Go is always pass by value - https://medium.com/@vivek_syngh/pass-by-value-and-pass-by-reference-in-go-8483534b7385 (this was based on 5 minute search on the golang)

Regardless, I do not agree with you that a field x y is same as x *y in a class. Why create the confusion? Can you please explain why having client *HttpClient would not work for you?

2021-10-06 03:54 UTC, grastogi23 commented on go/session/avisession.go
> +	if avisess.client == nil {
I didn't mean remove the nil check. Your code for checking for avisess.client == nil  will work even when you change to client *HttpClient.

2021-10-06 03:58 UTC, grastogi23 commented on go/session/avisession.go
> +func SetClient(client HttpClient) func(*AviSession) error {
Making it pointer does not mean it becomes pointer to pointer. It is value of pointer. It keeps the interface clean as lifecyle of the httpclient is outside of the sdk and it is maintained by the caller.

2021-10-06 03:58 UTC, aaronjwood commented on go/session/avisession.go
> +	client HttpClient
No worries. We can make it a pointer to a pointer if needed, I just didn't see the case for it. You're right that Go is pass by value, but in the same way that C is pass by value. Even though you have pointer types they can be passed around by value. Usually with C, or I guess Go if you had the use case, you work with double pointers when you want to change what it's pointing to (because of the constraints of pass by value)

What would be the benefit to having the field (now an interface) be a pointer to a pointer here?

2021-10-08 19:06 UTC, grastogi23 requested changes

2021-10-08 19:06 UTC, grastogi23 commented on go/session/avisession.go
> +		if avisess.transport == nil {
Please delete the lines 325 - 329 337-342 take care of that scenario.

2021-10-08 19:09 UTC, grastogi23 approved these changes

2021-10-11 03:58 UTC, mayank-avinetworks approved these changes

2021-10-11 04:03 UTC, mayank-avinetworks commented
run jenkins-go-sdk-ut

2021-10-11 04:04 UTC, mayank-avinetworks commented
run jenkins-go-sdk-ut

2021-10-11 05:10 UTC, ArpitAVI commented
run jenkins-go-sdk-ut

2021-10-11 05:58 UTC, ArpitAVI commented
run jenkins-go-sdk-ut

2021-10-11 06:04 UTC, ArpitAVI commented
run jenkins-go-sdk-ut

2021-10-11 06:42 UTC, ArpitAVI commented
run jenkins-go-sdk-ut

2021-10-11 15:09 UTC, mayank-avinetworks commented on go/session/avisession_test.go
> +	client := &stdhttp.Client{Timeout: 10 * time.Second}
@aaronjwood , Please set the transport and timeout for the external client by yourself here.

2021-10-12 07:34 UTC, mayank-avinetworks approved these changes

2021-10-12 08:02 UTC, yograjshisode commented
run jenkins-go-sdk-ut

2021-10-12 08:14 UTC, mayank-avinetworks commented
UT passed for TCs

2021-10-12 08:14 UTC, merged