Rt 16.3 netscalar policies
vmware/alb-sdk pull request #196
Opened 2017-02-07 15:00 UTC by rameshtathe

I have made the changes, Can you please review?

Made changes to update csv report fromat

2017-02-07 15:27 UTC, grastogi23 commented
can you pl. ensure all the conv_status with successful and partial have objects passed down.

2017-02-08 13:38 UTC, grastogi23 requested changes

2017-02-08 13:38 UTC, grastogi23 commented on python/avi/netscaler_converter/ns_util.py
> +            add_status_row(bind_cmd, b_cmd, full_cmd, STATUS_SUCCESSFUL)
should there be an object passed down when status is successful?

2017-02-08 13:38 UTC, grastogi23 commented on python/avi/netscaler_converter/ns_util.py
> +                add_status_row(cmd, policy_name, full_cmd, STATUS_SUCCESSFUL)
same here. shouldn't we pass the policy object / rule here?

2017-02-08 13:38 UTC, grastogi23 commented on python/avi/netscaler_converter/csvs_converter.py
> +                                LOG.info('Conversion successful : %s' % pl_cmd)
there is no add_status_row here. It seems to have been previously present

2017-02-08 13:38 UTC, grastogi23 commented on python/avi/netscaler_converter/csvs_converter.py
> +                    LOG.info('Conversion successful : %s' % clt_cmd)
I don't see replacement for add_status_row here.

2017-02-08 13:53 UTC, rameshtathe commented on python/avi/netscaler_converter/csvs_converter.py
> +                    LOG.info('Conversion successful : %s' % clt_cmd)
Here,  attribute clttimeout is successfully converted and added into the avi config object, though we add complete avi config object on completion of complete command conversion to CSV report. So here it is not required to add_status_row.

2017-02-08 13:55 UTC, rameshtathe commented on python/avi/netscaler_converter/csvs_converter.py
> +                                LOG.info('Conversion successful : %s' % pl_cmd)
@grastogi23 Exactly same case as above. Here we have successfully converted attribute and not complete command yet so not added to CSV report but we only update AVI config object here which is logged to CSV report on completion of complete command.

2017-02-08 15:27 UTC, grastogi23 approved these changes

2017-02-08 15:27 UTC, merged