Fix for #AV-17472 : F5 V10 conversion issue
vmware/alb-sdk pull request #217
Opened 2017-03-02 14:08 UTC by chaitanyaavi

2017-03-06 20:49 UTC, grastogi23 requested changes

2017-03-06 20:49 UTC, grastogi23 commented on python/avi/f5_converter/vs_converter.py
> +            if isinstance(f5_vs['rules'], str):
I believe you will need to check for both basestring and unicode...

2017-03-09 06:37 UTC, chaitanyaavi commented on python/avi/f5_converter/vs_converter.py
> +            if isinstance(f5_vs['rules'], str):
Updated check for basestring which will check for str and unicode both.

2017-03-09 19:25 UTC, grastogi23 approved these changes

2017-03-09 19:25 UTC, merged