Fixed: ssl cipher yaml file
vmware/alb-sdk pull request #224
Opened 2017-03-23 12:36 UTC by rameshtathe

I have made the changes to fix the ssl cipher yaml file

2017-03-23 14:54 UTC, grastogi23 requested changes

2017-03-23 14:54 UTC, grastogi23 commented on python/avi/netscaler_converter/profile_converter.py
> +        ssl_ciphers_dict = yaml.safe_load(open(os.path.dirname(__file__) + '/%s'
This is not the right place for resolving the directory. ssl_ciphers_yaml was passed as argument. This file name should be resolved properly there i.e netscaler_config_converter.py:31

2017-03-24 03:24 UTC, rameshtathe commented on python/avi/netscaler_converter/profile_converter.py
> +        ssl_ciphers_dict = yaml.safe_load(open(os.path.dirname(__file__) + '/%s'
Fixed.
load the ssl cipher yaml file in netscaler_config_converter.py and passed to profile converter

2017-03-24 04:48 UTC, grastogi23 approved these changes

2017-03-24 04:48 UTC, merged