Added new changes for migration hardening
vmware/alb-sdk pull request #274
Opened 2017-05-25 15:48 UTC by cjawale

2017-05-25 17:40 UTC, grastogi23 requested changes

2017-05-25 17:40 UTC, grastogi23 commented on python/avi/migrationtools/avi_converter.py
> -        if prefix:
seems like this getting rid of prefix.. is this expected?

2017-05-25 18:30 UTC, cjawale commented on python/avi/migrationtools/avi_converter.py
> -        if prefix:
Yes, this should be remove, because these were not the pull changes which CD has created PR for 
there was slight confusion in branch name while creating PR.
So these are the conflict changes which was tested yesterday.

2017-05-26 05:31 UTC, grastogi23 approved these changes

2017-05-26 05:31 UTC, merged