Converter hardening 2
vmware/alb-sdk pull request #285
Opened 2017-06-05 12:01 UTC by chaitanyaavi

2017-06-05 15:13 UTC, grastogi23 requested changes

2017-06-05 15:13 UTC, grastogi23 commented on python/avi/migrationtools/ansible/library/avi_traffic.py
> +            status_path = '/api/virtualservice/%s/runtime/detail/' % uuid
optional one would be to use inventory... sometimes that is better than using runtime.

2017-06-05 15:13 UTC, grastogi23 commented on python/avi/migrationtools/ansible/library/avi_traffic.py
>      response = requests.get(request_type + '://' + controller + path +
let us use the Avi ApiSession rather than requests library  for controller. This may become an issue later for openstack etc type environments.

2017-06-05 15:13 UTC, grastogi23 commented on python/avi/migrationtools/ansible/library/avi_traffic.py
>      response = requests.get(request_type + '://' + controller + path +
Also, it expects basic auth which may not be the case always.

2017-06-05 15:13 UTC, grastogi23 commented on python/avi/migrationtools/ansible/library/avi_traffic.py
> +                if 'OPER_UP' == response[0]['oper_status']['state']:
let us change to inventory. Also, tenant needs to be specified as well.

2017-06-05 15:13 UTC, grastogi23 commented on python/avi/migrationtools/ansible/library/avi_traffic.py
> +            stderr='Virtualservice api is not reachable',
I believe it should VIP not API

2017-06-05 15:13 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/conversion_util.py
> +        return None, None, None
should have a log here with reason for skip. Might be needed in debugging.

2017-06-05 15:13 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/conversion_util.py
> +        ips = filter(None, ips)
this does not seem right. If the goal is to remove any member that is not None then 
ips = [ip for ip in ips if ip]

2017-06-05 15:13 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/monitor_converter.py
> +                    'qname') == 'none'):
'none' does not seem right....

2017-06-05 15:13 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/pool_converter.py
>                  server_obj['port'] = port
add debug when condition is not true?

2017-06-05 15:13 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/vs_converter.py
> +        if self.con_snatpool:
we should may be print message if  snat = f5_vs.get("source-address-translation", {}) is not empty and flag self.con_snatpool is set. This way information would be there in log as why snat was skipped.

2017-06-06 11:41 UTC, cjawale commented on python/avi/migrationtools/f5_converter/pool_converter.py
>                  server_obj['port'] = port
Done. Added debug log when condition is not true.

2017-06-06 12:30 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/monitor_converter.py
> +                    'qname') == 'none'):
F5 input file may have string value as 'none' added this condition to avoid that scenario.

2017-06-07 16:26 UTC, grastogi23 approved these changes

2017-06-07 16:27 UTC, merged