Av 23610 : Added progress bar for F5 and netscaler
vmware/alb-sdk pull request #327
Opened 2017-07-18 12:59 UTC by chaitanyaavi

2017-07-18 19:32 UTC, grastogi23 requested changes

2017-07-18 19:32 UTC, grastogi23 commented on python/avi/migrationtools/avi_converter.py
> +                       length=100, fill='#'):
should length be 80 for 80 char window. or may be just 50 so it does not wrap around?

2017-07-18 19:32 UTC, grastogi23 commented on python/avi/migrationtools/config_patch.py
> +        print "Conversion For Patching of Object started..."
Patching of objects

2017-07-20 16:40 UTC, grastogi23 requested changes

2017-07-20 16:40 UTC, grastogi23 commented on python/avi/migrationtools/config_patch.py
> +        from avi.migrationtools.avi_converter import print_progress_bar
why we are importing it here?

2017-07-20 16:40 UTC, grastogi23 commented on python/avi/migrationtools/gss_convertor/gss_parser.py
> +    LOG.info('Parserend Started')
spelling

2017-07-21 06:49 UTC, chaitanyaavi commented on python/avi/migrationtools/config_patch.py
> +        from avi.migrationtools.avi_converter import print_progress_bar
There is cyclic dependency on config_patch.py and avi_converter.py hence we had to import it here.

2017-07-21 18:06 UTC, grastogi23 commented on python/avi/migrationtools/config_patch.py
> +        from avi.migrationtools.avi_converter import print_progress_bar
let us then move the print_progress_bar into a common migration_utils.py

2017-07-25 14:36 UTC, grastogi23 requested changes

2017-07-25 14:36 UTC, grastogi23 commented on python/avi/migrationtools/avi_migration_utils.py
> +class Migration_Utils(object):
we don't use _ in the class names. so it should be MigrationUtils

2017-07-25 14:36 UTC, grastogi23 commented on python/avi/migrationtools/avi_migration_utils.py
> +class Ns_Migration_Utils(Migration_Utils):
Ns_Migration_Utils -> NsMigrationUtils

2017-07-25 17:18 UTC, grastogi23 approved these changes

2017-07-25 17:18 UTC, merged