AV23642: Baseprofile merge review comment. Do not merge.
vmware/alb-sdk pull request #328
Opened 2017-07-18 16:39 UTC by Rishabh-Baranwal

2017-07-19 13:44 UTC, grastogi23 requested changes
Hi
Let us review the object comparison. as it seems like it is only happening using name which is not sufficient.

2017-07-19 13:44 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/f5_config_converter.py
> +merge_object_mapping = {
can this be generic... there are other profiles too that can benefit from merging.

2017-07-19 13:44 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/f5_config_converter.py
> +        sys_dict['ApplicationProfile'] = []
also do 
merge_obj_types = ['NetworkProfile', 'SSLProfile'...]
for obj_type in merge_obj_types.keys():
   sys_dict[obj_type] = []

2017-07-19 13:44 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/f5_config_converter.py
> +                sys_dict['ApplicationProfile'] = \
again this can be 
for k in merge_obj_types.keys()
   sys_dict[k] = prof_data.get(k, [])

2017-07-19 13:44 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/f5_config_converter.py
> +        avi_config_dict["SSLProfile"] = []
this can be simplified too.

2017-07-19 13:44 UTC, grastogi23 commented on python/avi/migrationtools/netscaler_converter/netscaler_config_converter.py
> +        sys_dict["SSLProfile"] = []
this code should be common in some place...

2017-07-19 13:44 UTC, grastogi23 commented on python/avi/migrationtools/netscaler_converter/ns_util.py
> +            return obj["name"], src_obj['name']
name matching may not be sufficient as two netscalers conf may have different objects with same name.

2017-07-19 13:44 UTC, grastogi23 commented on python/avi/migrationtools/netscaler_converter/ns_util.py
>          del tmp_cp["name"]
you can use tmp_cp.pop instead. It has option to ignore check for keys.

2017-07-19 14:31 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/netscaler_converter/ns_util.py
> +            return obj["name"], src_obj['name']
Sorry Gaurav, correct me if am wrong. We merge profile/monitor on basis of all attributes/keys except 'description' and 'name' as we delete it before comparison.

2017-07-19 14:36 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/netscaler_converter/ns_util.py
> +            return obj["name"], src_obj['name']
Also for System profiles we remove 'url' and 'uuid' keys/attributes before comparison

2017-07-19 14:55 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/f5_converter/f5_config_converter.py
> +merge_object_mapping = {
the dict is having all entities which comes as a result from conversion and needs merging. I agree with you but can we go ahead with this as of now , will check the possibility.

2017-07-20 16:44 UTC, grastogi23 approved these changes

2017-07-20 16:44 UTC, grastogi23 commented
AV-23642 #commit

2017-07-20 16:45 UTC, merged