AV 21016: Validation method completed.  [Do not merge]
vmware/alb-sdk pull request #353
Opened 2017-08-09 15:00 UTC by Rishabh-Baranwal

2017-08-18 13:29 UTC, grastogi23 commented
@Rishabh-Baranwal pl. rebase to 17.1.6

2017-08-22 14:51 UTC, grastogi23 commented
@Rishabh-Baranwal  pl. add unit tests.

2017-08-23 22:15 UTC, grastogi23 requested changes

2017-08-23 22:15 UTC, grastogi23 commented on python/avi/migrationtools/avi_migration_utils.py
> +        new_value = value if value is not None else None
why check for None. you can simply do new_value = value. It would be the same behavior.

2017-08-23 22:15 UTC, grastogi23 commented on python/avi/migrationtools/avi_migration_utils.py
> +            LOG.debug("Validating property '%s'" % ('-->'.join(entity_names) +
use the format style debugging. This will result in evaluation of arguments regardless of whether debug is turned on or off.
eg. log.debug("%s", x) instead of log.debug("%s" % x)

2017-08-23 22:15 UTC, grastogi23 commented on python/avi/migrationtools/avi_migration_utils.py
> +            if type(new_value) == unicode:
may want to check for basestring as well.

2017-08-23 22:15 UTC, grastogi23 commented on python/avi/migrationtools/avi_migration_utils.py
> +                        new_value = False if new_value == 'False' else True
what if new_value == False instead of 'False'. this logic would make it True.

2017-08-23 22:15 UTC, grastogi23 commented on python/avi/migrationtools/avi_migration_utils.py
> +            if eval(p_key.get('required')):
why eval?

2017-08-24 06:37 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/avi_migration_utils.py
> +        new_value = value if value is not None else None
sorry, I didn't realize that I have a cover made by me at line 260, will remove that.

2017-08-24 06:37 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/avi_migration_utils.py
> +            LOG.debug("Validating property '%s'" % ('-->'.join(entity_names) +
Ok, will do that for every debug line.

2017-08-24 06:37 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/avi_migration_utils.py
> +            if type(new_value) == unicode:
I hadn't seen python type returning from protobuf as unicode or basestring, had seen 'str' only by far. Hence, need to encode the unicode value to make it python type 'str'. If I use basestring check, it will be true for both unicode and str then I will not be able to decide which one to encode to make it proper str.

2017-08-24 06:38 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/avi_migration_utils.py
> +                        new_value = False if new_value == 'False' else True
I believe, new_value can't be False as p_key.get('default_value') will give either 'True' or 'False'.

2017-08-24 06:38 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/avi_migration_utils.py
> +            if eval(p_key.get('required')):
ok, I will check for 'True' directly.

2017-08-24 16:07 UTC, merged