F5 policy conversion for F5 v11 config file
vmware/alb-sdk pull request #406
Opened 2017-09-15 14:16 UTC by Rishabh-Baranwal

2017-09-15 15:06 UTC, grastogi23 requested changes

2017-09-15 15:06 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/conversion_util.py
> +        :param clone_for: Name of the VS for pool to be cloned
should this be clone_of_xxx

2017-09-15 15:06 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/conversion_util.py
> +                                if http_req.get('switching_action',{}):
let us split into another function. This is too long.

2017-09-15 15:06 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/conversion_util.py
> +    def get_skipped_pool(self, avi_config, pool_name, pool_csv_rows,
add comments with high level logic

2017-09-15 15:06 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/conversion_util.py
> +        if 'health_monitor_refs' in pool_object[0]:
we should have a check for pool_object. If pool_object is empty [] then [0] will fail. Also, let us call it pool_objects or do pool_object = pool_object[0] if pool_object else None.

2017-09-15 15:06 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/conversion_util.py
> +            if rule.get('switching_action'):
instead do if 'switching_action' in rule:

2017-09-15 15:06 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/vs_converter.py
> +        if 'policies' in f5_vs:
split this into a smaller function.

2017-09-18 13:37 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/f5_converter/conversion_util.py
> +        :param clone_for: Name of the VS for pool to be cloned
It should be clone_for as we do cloning of pool/pool group for vs and policy

2017-09-18 13:37 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/f5_converter/conversion_util.py
> +                                if http_req.get('switching_action',{}):
changes as asked

2017-09-18 13:37 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/f5_converter/conversion_util.py
> +            if rule.get('switching_action'):
changed as asked

2017-09-18 13:37 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/f5_converter/conversion_util.py
> +    def get_skipped_pool(self, avi_config, pool_name, pool_csv_rows,
Added the doc string

2017-09-18 13:37 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/f5_converter/conversion_util.py
> +        if 'health_monitor_refs' in pool_object[0]:
Added the pool_object check

2017-09-18 13:38 UTC, Rishabh-Baranwal commented on python/avi/migrationtools/f5_converter/vs_converter.py
> +        if 'policies' in f5_vs:
changed as asked

2017-09-19 00:25 UTC, grastogi23 approved these changes

2017-09-19 00:25 UTC, merged