AV-27828 Added option to use uuid when it is present in object to per…
vmware/alb-sdk pull request #442
Opened 2017-10-05 13:47 UTC by chaitanyaavi

…form GET: Ansible

2017-10-05 15:27 UTC, grastogi23 requested changes

2017-10-05 15:27 UTC, grastogi23 commented on python/avi/sdk/utils/ansible_utils.py
> +    elif not name and not uuid:
no need to test for not uuid as it will never come here if uuid was set.

2017-10-05 15:27 UTC, grastogi23 commented on python/avi/sdk/utils/ansible_utils.py
> +        existing_obj = api.get(obj_path, tenant=tenant, tenant_uuid=tenant_uuid,
we may need to test for exception here. because if object is not present the .json() may result in failure.

2017-10-05 15:51 UTC, grastogi23 requested changes

2017-10-05 15:51 UTC, grastogi23 commented on python/avi/sdk/utils/ansible_utils.py
> +            return
you can't return from here. It has to be 
return module.fail_json(msg=rsp.text)

try to create this scenario using playbook as test to make sure we get intended behavior.

2017-10-06 05:31 UTC, chaitanyaavi commented on python/avi/sdk/utils/ansible_utils.py
> +            return
Tested with return module.fail_json(msg=rsp.text) for incorrect uuid. Got following response on console.

TASK [Create or Update virtualservice: triageavailability-prdap-lv.cfp.intuit.net_8080] *******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "{\"error\": \"VirtualService object not found!\"}"}
	to retry, use: --limit @/home/vinay/avi_config_create_object.retry

PLAY RECAP ************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1  

Is it expected behavior?

2017-10-06 18:46 UTC, grastogi23 requested changes

2017-10-06 18:46 UTC, grastogi23 commented on python/avi/sdk/utils/ansible_utils.py
> +            return module.fail_json(msg=existing_obj.text)
I reviewed the code again. I believe here it should simply be except for object not found should be existing_obj = None. this way later part of the code can do post as object was not found.

2017-10-12 05:47 UTC, grastogi23 requested changes

2017-10-12 05:47 UTC, grastogi23 commented on python/avi/sdk/utils/ansible_utils.py
> +            existing_obj = existing_obj.json()
It is better to catch the special object not found exception defined in the avi_api.py.

2017-10-17 14:46 UTC, grastogi23 approved these changes

2017-10-17 14:46 UTC, merged