fixes for duplicate domains in Gss
vmware/alb-sdk pull request #450
Opened 2017-10-06 15:46 UTC by Jeyanthinath

2017-10-06 18:42 UTC, grastogi23 requested changes

2017-10-06 18:42 UTC, grastogi23 commented on python/avi/migrationtools/gss_convertor/gss_config_convertor.py
> +    # fix for multiple az
can we break this into a different function. Too long makes it hard to read.

2017-10-07 08:39 UTC, Jeyanthinath commented on python/avi/migrationtools/gss_convertor/gss_config_convertor.py
> +    # fix for multiple az
ok

2017-10-09 15:33 UTC, Jeyanthinath commented on python/avi/migrationtools/gss_convertor/gss_config_convertor.py
> +    # fix for multiple az
fixed

2017-10-10 03:39 UTC, grastogi23 approved these changes

2017-10-10 03:39 UTC, merged