Av 23893
vmware/alb-sdk pull request #462
Opened 2017-10-10 13:15 UTC by chaitanyaavi

2017-10-11 05:07 UTC, grastogi23 requested changes

2017-10-11 05:07 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> -        self.controller_ip = controller_ip
let us add property decorators for all the fields that are getting deprecated. Also, add setters for them too which will update the avi_credentials that is cached.

2017-10-11 05:07 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +                 retry_conxn_errors=True, data_log=False, avi_credentials=None):
add documentation that ApiSession takes ownership and may update the information inside it.

2017-10-12 15:55 UTC, grastogi23 approved these changes

2017-10-12 15:55 UTC, grastogi23 commented
@chaitanyaavi pl. also add test cases for the getters and setters.

2017-10-18 00:02 UTC, nmandeyam reviewed
Chaitanya, 

Can we get this into 17.1.10, 17.2.3 and eng-top.?

Narasimhan

2017-10-18 00:02 UTC, nmandeyam approved these changes

2017-10-31 14:36 UTC, grastogi23 approved these changes

2017-10-31 14:36 UTC, merged