Av 27817 Unify ApiSession authentication requests for basic and token auth
vmware/alb-sdk pull request #466
Opened 2017-10-10 23:50 UTC by nparikh-avinetworks

2017-10-11 04:43 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +        self.token = token
we shouldn't change the name... I am not sure if there is code that is accessing it with that name. 
@ypraveen: Added him for review on this as his os and heat plugins might be using it.

2017-10-11 04:47 UTC, grastogi23 requested changes

2017-10-11 04:47 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +            "token": self.token,
Was this causing problems? Isn't it better to not send empty strings for password or token?

2017-10-11 04:47 UTC, grastogi23 commented on python/avi/sdk/samples/cust_scripts/server_down_script.py
> +    rsp = requests.post(os.path.join(ws_addr, 'login'), verify=False,
let us convert this to use the SDK itself. Anyway this bad code and should actually be deleted.

2017-10-11 04:49 UTC, grastogi23 commented
@chaitanyaavi Added CD as he is bringing sweeping changes to SDK and that would need to be merged with this change.

2017-10-12 18:15 UTC, ypraveen commented on python/avi/sdk/avi_api.py
> +        self.token = token
I am not accessing keystone_token directly.

2017-10-12 21:22 UTC, nparikh-avinetworks commented on python/avi/sdk/avi_api.py
> +            "token": self.token,
We modified the permissions code to put the onus of deciding which credentials to use on the authentication logic allowing empty strings and None values to be  handled gracefully by default.

2017-10-12 21:38 UTC, nparikh-avinetworks commented on python/avi/sdk/avi_api.py
> +        self.token = token
@grastogi23 @ypraveen 
Given that `keystone_token` doesn't appear to be used directly is it ok to keep this change? I renamed this attr because `token`  is being used for both keystone and API token auth. (I realize though that we are not the only consumers of this SDK so I should be more careful about this kind of change in the future).

2017-10-12 21:47 UTC, nparikh-avinetworks commented on python/avi/sdk/samples/cust_scripts/server_down_script.py
> +    rsp = requests.post(os.path.join(ws_addr, 'login'), verify=False,
I see what you mean. I assume the preferred why to login is by creating a valid ApiSession. Should I modify the example to use an ApiSession, delete the example, or make a different change here?

2017-10-12 21:53 UTC, ypraveen commented on python/avi/sdk/avi_api.py
> +        self.token = token
I am fine with renaming it. "token" is better than "keystone_token".

2017-10-13 02:53 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +        self.token = token
This field is anyway getting deprecated. https://github.com/avinetworks/sdk/pull/462. I would leave this change. I will ask CD to provide property for token. I am assuming there is not much folks in OS using API SDK directly.

2017-10-13 02:54 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +            "token": self.token,
but SDK could be used cross versions. I would pass on this change as we have many situations where customers use newer SDK with different versions of controller.

2017-10-13 02:55 UTC, grastogi23 commented on python/avi/sdk/samples/cust_scripts/server_down_script.py
> +    rsp = requests.post(os.path.join(ws_addr, 'login'), verify=False,
If you are enhancing the code then change everything to ApiSession as requests library do not handle things like CSRF token etc. Otherwise, I will leave it up to you based on your time to modify it.

2017-10-14 00:20 UTC, merged