fixes the some missed clone pools
vmware/alb-sdk pull request #496
Opened 2017-11-10 13:15 UTC by Jeyanthinath

2017-11-10 18:13 UTC, grastogi23 requested changes

2017-11-10 18:13 UTC, grastogi23 commented on python/avi/migrationtools/ace_converter/vs_converter.py
> +                if pool.get('application_persistence_profile_ref', '') or l4_type:
why not use and like

if (pool['name'] == pool_name) and (pool.get('application_persistence_profile_ref', '') or l4_type) and l4_type): 

Also, if the final condition is only based on l4_type then above logic is not right.

2017-11-13 16:41 UTC, Jeyanthinath commented on python/avi/migrationtools/ace_converter/vs_converter.py
> +                if pool.get('application_persistence_profile_ref', '') or l4_type:
fixed that , we are returning True in both that cases , also if l4 is there with other than client based ip address we are additionally removing it

2017-11-13 18:38 UTC, grastogi23 requested changes

2017-11-13 18:38 UTC, grastogi23 commented on python/avi/migrationtools/ace_converter/vs_converter.py
> +            if pool['name'] == pool_name and (pool.get('application_persistence_profile_ref', '') or l4_type):
seems like the right logic is 
if pool['name'] == pool_name and pool.get('application_persistence_profile_ref') and l4_type

because next if will only get executed if l4_type is true.

2017-11-13 20:35 UTC, Jeyanthinath commented on python/avi/migrationtools/ace_converter/vs_converter.py
> +            if pool['name'] == pool_name and (pool.get('application_persistence_profile_ref', '') or l4_type):
we are returning true on if any one of the "pool.get('application_persistence_profile_ref')"  or "l4_type" is present. 

The nested l4 if loop is to check and removing the application persistence over here

2017-11-13 21:11 UTC, grastogi23 approved these changes

2017-11-13 21:11 UTC, merged