AV-31637 - Golang SDK Features & Bug Fixes
vmware/alb-sdk pull request #522
Opened 2017-12-18 23:53 UTC by RahulMitra

Golang SDK:
* Add support for token based authentication AviSession
* API versioning, fixed to AviSession
* Bug fixes
* Update unit tests for both credentials and auth token session types

2017-12-19 18:55 UTC, grastogi23 requested changes

2017-12-19 18:55 UTC, grastogi23 commented on go/session/avisession.go
> +	output, err := exec.Command("/opt/avi/python/bin/portal/manage.py", "gen_auth_token", "--user", "admin", "--hours", "12").Output()
this should not kept in the SDK as SDK is expected to run outside controller too. Rather have an api that takes argument of token. This code should be part of the internal AVI controller code and not exposed out.

2017-12-19 18:55 UTC, grastogi23 commented on go/session/avisession.go
> +		return sess.setTenant(version)
this should be setVersion rather than setTenant

2017-12-19 18:55 UTC, grastogi23 commented on go/session/avisession.go
> +	tokenAuth bool
we have two fields with confusing names tokenAuth and authToken. can we change this one to useTokenAuth. and also keep it together with the authtoken param.

2017-12-19 18:55 UTC, grastogi23 commented on go/session/avisession.go
> +	if resp.StatusCode == 401 && avisess.tokenAuth {
again, this code should be outside the avisess sdk. may be we allow callers to register a callback function to refresh token. And then the caller can supply the new token everytime there is 401 and use token is set.

2017-12-19 18:55 UTC, grastogi23 commented on go/session/session_test.go
> +		"admin", SetPassword("avi123"), SetInsecure)
though it is old code. pl. change password to something other than avi123

2017-12-19 18:55 UTC, grastogi23 commented on go/session/session_test.go
> +func testAviPool(t *testing.T, avisess *AviSession) {
let us keep it consistent whether to have every test start with Caps or not. I don't know what is the Go Preferred way

2017-12-19 19:02 UTC, ypraveen commented on go/clients/avi_client.go
> +	GslbApplicationPersistenceProfile *GslbApplicationPersistenceProfileClient
AviClient changes should be done in a separate commit, as they are version specific.

2017-12-19 19:04 UTC, ypraveen commented on go/session/avisession.go
> +	// tokenAuth specifies whether we should use an authenticatoin token
typo in authentication

2017-12-19 21:57 UTC, RahulMitra commented on go/clients/avi_client.go
> +	GslbApplicationPersistenceProfile *GslbApplicationPersistenceProfileClient
Praveen, when I pulled the code from master, it would not compile without these additional changes. This is because the NewAviClient function tries to assign this field, which prior did not exist: 	aviClient.GslbApplicationPersistenceProfile = NewGslbApplicationPersistenceProfileClient(aviSession)

2017-12-19 21:59 UTC, RahulMitra commented on go/session/session_test.go
> +func testAviPool(t *testing.T, avisess *AviSession) {
This is actually the correct way for go. When structuring go unit tests, the tests which are run must have the format Test{FunctionName}. This is a decomposed helper function that is called by TestAviPool, the top-level function, so it must be lower case.

2017-12-19 23:07 UTC, grastogi23 requested changes

2017-12-19 23:07 UTC, grastogi23 commented on go/session/avisession.go
> +	if resp.StatusCode == 401 && avisess.isTokenAuth() {
if session expired then would it always take the line 328 branch? all of them would be true in that case?

2017-12-19 23:07 UTC, grastogi23 commented on go/session/avisession.go
> +			emsg := "Invalid Auth Token"
We should preserve the message from the resp rather than masking it with "Invalid auth token". This would be helpful in case of understanding why did controller reject and any additional clues it provided. Additionally, you can add no refresh token function supplied.

2017-12-19 23:13 UTC, vivek-avi commented on go/session/avisession.go
> +			return avisess.restRequest(verb, uri, payload)
if the token authentication fails constantly, could this become an infinite loop ?

2017-12-19 23:14 UTC, vivek-avi commented on go/session/avisession.go
> +			return avisess.restRequest(verb, uri, payload)
same issue can happen with the initiateSession() logic above, it needs to check the error returned by initiateSession and return on failure.

2017-12-19 23:56 UTC, RahulMitra commented on go/session/avisession.go
> +	if resp.StatusCode == 401 && avisess.isTokenAuth() {
I believe this to be the case. This is because the session ID has been set, and is not hitting the login URL, yet we got a 401. I believe this check is necessary because initiateSession itself makes a POST to the /login route, which therefore calls this function, so we don't want to get stuck in an infinite loop.

2017-12-20 01:19 UTC, RahulMitra commented on go/session/avisession.go
> +			return avisess.restRequest(verb, uri, payload)
Implemented a counting mechanism and some crude backoff for retrying to avoid infinite loop.

2017-12-20 18:25 UTC, grastogi23 approved these changes

2017-12-20 18:29 UTC, merged