Inventory for f5
vmware/alb-sdk pull request #530
Opened 2018-01-02 16:54 UTC by Rishabh-Baranwal

2018-02-21 17:07 UTC, grastogi23 commented
@Jeyanthinath @Rishabh-Baranwal  let us rebase it to 17.2.8

2018-02-21 19:51 UTC, Jeyanthinath commented
@grastogi23 rebased, But please don't merge it now

2018-02-21 19:56 UTC, grastogi23 requested changes
let us change the dependency on f5-sdk and bigsuds

2018-02-21 19:56 UTC, grastogi23 commented on python/avi/migrationtools/setup.py
> +                      'unittest2', 'networkx', 'f5-sdk', 'bigsuds'],
we cannot have these tools be installed by avi. We need to raise proper error if f5-sdk and bigsuds is not found.

2018-02-21 19:58 UTC, Jeyanthinath commented on python/avi/migrationtools/setup.py
> +                      'unittest2', 'networkx', 'f5-sdk', 'bigsuds'],
so we need to through exceptions at run time if the packages or not found , isn't it ?

2018-02-21 20:57 UTC, grastogi23 commented
Yes. Also this way those libraries would not get packed with controller and
customers will install them.

Gaurav Rastogi
Avi Networks


On Feb 21, 2018, at 11:58 AM, Jeyanthinath MuthuRam <
notifications@github.com> wrote:

*@Jeyanthinath* commented on this pull request.
------------------------------

In python/avi/migrationtools/setup.py
<https://github.com/avinetworks/sdk/pull/530#discussion_r169759928>:

> @@ -33,7 +34,7 @@
                       'pycrypto', 'ecdsa', 'pyOpenssl', 'nose-html-reporting',
                       'nose-testconfig', 'ConfigParser',
'xlsxwriter', 'jinja2',
                       'pandas', 'openpyxl', 'appdirs',  'pexpect',
-                      'unittest2', 'networkx'],
+                      'unittest2', 'networkx', 'f5-sdk', 'bigsuds'],

so we need to through exceptions at run time if the packages or not found ,
isn't it ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/avinetworks/sdk/pull/530#discussion_r169759928>, or mute
the thread
<https://github.com/notifications/unsubscribe-auth/ADrBfwKyXOjNxmyDmuVWyFoHfKNqMVGSks5tXHVbgaJpZM4RQ1Hp>
.

2018-03-01 12:50 UTC, grastogi23 commented on python/avi/migrationtools/f5_inventory.py
> +    print "Please Install bigsuds and f5 sdk's to proceeed.."
We should Log error as print may not work. Also, don't continue after this point. Simply raise the exception again.

2018-03-05 05:05 UTC, Jeyanthinath commented on python/avi/migrationtools/f5_inventory.py
> +    print "Please Install bigsuds and f5 sdk's to proceeed.."
ok will exit the code after raising the exception

2018-03-05 19:12 UTC, grastogi23 commented
@Rishabh-Baranwal @Jeyanthinath do we still keep this out?

2018-03-06 15:01 UTC, grastogi23 requested changes

2018-03-06 15:01 UTC, grastogi23 commented on python/avi/migrationtools/setup.py
> +                      'unittest2', 'networkx', 'f5-sdk', 'bigsuds'],
this is back... we should remove 'f5-sdk', 'bigsuds' dependencies

2018-03-06 15:41 UTC, Jeyanthinath commented
removed the package dependency from setup.py

2018-03-06 15:49 UTC, grastogi23 approved these changes

2018-03-06 15:52 UTC, merged