Av 37800 Add support for crypto object mapping in AVI config converter.
vmware/alb-sdk pull request #621
Opened 2018-04-17 09:28 UTC by gitshrikant

Added support for crypto chain-group object and successfully uploaded configuration to Avi controller.

2018-04-17 14:42 UTC, grastogi23 requested changes

2018-04-17 14:42 UTC, grastogi23 commented on python/avi/migrationtools/ace_converter/ace_converter.py
> +                        help='Out file location',default='.')
there should be space before deafult.

2018-04-17 14:42 UTC, grastogi23 commented on python/avi/migrationtools/ace_converter/ace_parser.py
> +                           'probe', 'action-list','crypto']
space after comma

2018-04-17 14:42 UTC, grastogi23 commented on python/avi/migrationtools/ace_converter/ace_parser.py
> +                    if len(temp_dict.keys()) > 1:
if temp_dict:

2018-04-17 14:42 UTC, grastogi23 commented on python/avi/migrationtools/ace_converter/ace_parser.py
> +                    elif 'rserver' in match:
add comments on significance of 3, 4, etc. give an example of how it is breaking up .

2018-04-17 14:42 UTC, grastogi23 commented on python/avi/migrationtools/ace_converter/ace_parser.py
> +            if key == 'crypto':
let us break up into smaller code chunks.

2018-04-18 10:05 UTC, gitshrikant reviewed
Done with the suggested changes.

2018-04-19 12:33 UTC, chaitanyaavi commented on python/avi/migrationtools/ace_converter/ace_parser.py
> -        grammer_4_2 = Group(Keyword('description') + restOfLine)
Should be restOfLine only test with description having blank spaces

2018-04-19 18:03 UTC, grastogi23 approved these changes

2018-04-23 17:45 UTC, grastogi23 approved these changes

2018-04-23 17:46 UTC, merged