Add cloning between controllers. Support more complex configurations.…
vmware/alb-sdk pull request #646
Opened 2018-05-23 14:43 UTC by thebertster

Code rewritten to be more modular and extensible. Now handles cloning to a different controller and more complex configurations. Also added options to force cloning of certain child objects rather than re-using them (e.g. application profile, health monitors etc.). Miscellaneous other enhancements.

2018-06-20 13:17 UTC, grastogi23 requested changes

2018-06-20 13:17 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
> +        if t_obj:
let us break this into smaller sections such that it can be better maintained in future.

2018-06-20 13:17 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
> +            otenant_uuid = ot_obj['uuid']
seems like this can be separted out into another method that is invoked for t_obj and ot_obj

2018-06-20 13:17 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
> +    VALID_POOL_REF_OBJECTS = {
we may need to add pool group support too. Specially verizon is using pool groups.

2018-06-20 13:17 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
>          if resp.status_code in (401, 419):
sdk is already doing these you don't need to do this again.

2018-06-20 13:17 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
> +        api._update_session_last_used()
same here. sdk is already doing it internally.

2018-06-20 13:17 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
> +        logger.debug('Cloning %s "%s" to "%s"', object_type,
split code to be in two lines.

2018-06-20 13:17 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
> +            # If an exception occurred, delete any intermediate objects we
This would be important thing to implement. alternatively, you can collect all objects and use api/macro to create them in one go. Not sure if you aware of it. I can go over with you about intro to macro api.

2018-06-20 13:18 UTC, grastogi23 requested changes

2018-06-20 13:18 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
> +cloud than the source - the destination may also be on a different Avi Vantage
let us make this part of the help message for the script. It would be very useful in the field.

2018-06-20 13:55 UTC, thebertster commented on python/avi/sdk/samples/clone_vs.py
> +    VALID_POOL_REF_OBJECTS = {
Cloning of Pool Groups is already catered for. This dictionary just lists a set of attributes which the user can specify to be forcibly cloned rather than re-used. I couldn't see any obvious pool group attributes that would need this treatment.

2018-06-20 13:57 UTC, thebertster commented on python/avi/sdk/samples/clone_vs.py
> +        api._update_session_last_used()
get_all_objects_by_name() is simply a straight copy of the get_object_by_name() from the SDK but instead of returning only the first object matching the name, returns all objects. I think we discussed this last time we reviewed the code and there was a suggestion to add this function directly to the SDK as it would be useful elsewhere...

2018-06-20 13:58 UTC, thebertster commented on python/avi/sdk/samples/clone_vs.py
>          if resp.status_code in (401, 419):
get_all_objects_by_name() is simply a straight copy of the get_object_by_name() from the SDK but instead of returning only the first object matching the name, returns all objects. I think we discussed this last time we reviewed the code and there was a suggestion to add this function directly to the SDK as it would be useful elsewhere...

2018-06-20 14:00 UTC, thebertster commented on python/avi/sdk/samples/clone_vs.py
> +            # If an exception occurred, delete any intermediate objects we
This is already fully implemented.

2018-06-20 14:01 UTC, thebertster commented on python/avi/sdk/samples/clone_vs.py
> +        logger.debug('Cloning %s "%s" to "%s"', object_type,
Could you clarify what you need to see here?

2018-06-20 22:21 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
> +        logger.debug('Cloning %s "%s" to "%s"', object_type,
logger.debug('Cloning %s "%s" to "%s"', object_type,
    old_name, new_name)

2018-06-20 22:21 UTC, grastogi23 commented on python/avi/sdk/samples/clone_vs.py
> +        # If run with no parameters, display general help text for the script
Pl. look at        https://github.com/avinetworks/sdk/blob/e142a13e0e0f3e4fadf61357d9c2f59acf8e606a/python/avi/migrationtools/f5_converter/f5_converter.py#L438

on how you can pass the help string to the arg parser
ideally don't want to be mixing logger and printf

2018-06-21 05:41 UTC, thebertster commented on python/avi/sdk/samples/clone_vs.py
> +        # If run with no parameters, display general help text for the script
OK, will do. I did it that way first, but didn't like the way it wrapped the text.

2018-06-21 22:50 UTC, grastogi23 approved these changes

2018-06-21 22:50 UTC, merged

2018-06-21 22:50 UTC, grastogi23 commented
done