AV-40602 #comment Added support for user CRUD operation.
vmware/alb-sdk pull request #723
Opened 2018-08-10 12:28 UTC by gitshrikant

Added support for username and password fields for user module.

2018-08-10 18:35 UTC, grastogi23 requested changes

2018-08-10 18:35 UTC, grastogi23 commented on python/avi/sdk/utils/ansible_utils.py
> +    for k in POP_FIELDS:
If you move this up then obj_username would always be popped so username will never be passed down. Did the test work?

2018-08-11 14:45 UTC, gitshrikant commented on python/avi/sdk/utils/ansible_utils.py
> +    for k in POP_FIELDS:
yes. The test did work. Earlier it was always poping username and password that's why I moved it up. Now it is not poping the username and password field and it does work.

2018-08-16 19:09 UTC, grastogi23 commented
How about we only allow user module to use api_credential. then there will be no issues?

2018-08-17 14:18 UTC, grastogi23 approved these changes

2018-08-17 14:19 UTC, grastogi23 approved these changes

2018-08-17 14:19 UTC, merged