Modified controller wait for response code 500. Cluster creation is successful after this change.
vmware/alb-sdk pull request #750
Opened 2018-10-03 11:54 UTC by gitshrikant

2018-10-05 20:29 UTC, grastogi23 requested changes
see attached

2018-10-05 20:29 UTC, grastogi23 commented on go/session/avisession.go
> +			if state_resp.StatusCode != 503 && state_resp.StatusCode != 502 && state_resp.StatusCode != 500 {
better way to code would be to say state_resp.StatusCode not in (503, 502, 500)

2018-10-06 12:50 UTC, gitshrikant commented on go/session/avisession.go
> +			if state_resp.StatusCode != 503 && state_resp.StatusCode != 502 && state_resp.StatusCode != 500 {
I think there is no built-in operator (like 'not in' ) to do it in Go. Otherwise, we need to iterate over the array.

2018-10-11 15:39 UTC, grastogi23 approved these changes

2018-10-11 15:39 UTC, merged