num_api_retries added instead  num_session_retries in _api
vmware/alb-sdk pull request #792
Opened 2018-11-22 06:56 UTC by shubhamavi

2018-11-27 01:17 UTC, grastogi23 requested changes
let us test that it actually works. based on the code it is not modifying the logic but simply changing the variable names.

2018-11-27 01:17 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +            self.num_api_retries += 1
can we not simply use num_session_retries instead of num_api_retries?

2018-11-27 05:56 UTC, shubhamavi commented on python/avi/sdk/avi_api.py
> +            self.num_api_retries += 1
Since `reset_session` resets the value of `num_session_retries` (which was causing the loop), there is, I think a need to track the retries by another counter, independent of `num_session_retries`.
I tested this by explicitly clearing the cookies every time we make an API request (in `def _api`) and this works well (stops retry attempts).
If we go ahead and use `num_session_retries`, we'll need a separate variable which forces it to NOT reset `num_session_retries` when a 401/419 is received in response to an API call. The current solution seemed more straightforward and simple.

2018-11-27 16:29 UTC, grastogi23 approved these changes

2018-11-27 16:29 UTC, merged

2018-11-28 06:49 UTC, shubhamavi commented
AV-46644