allow controller as entity_type
vmware/alb-sdk pull request #826
Opened 2018-12-21 17:55 UTC by ericsysmin

2018-12-21 18:06 UTC, grastogi23 requested changes
pl. see the comments.

2018-12-21 18:06 UTC, grastogi23 commented on python/avi/sdk/utils/api_utils.py
> +        if entity_type == 'controller':
this may not be enough.. the line 77 may fail. can you try to see it works? also commit it to 18.2.2 branch so it gets bundled with the controller as well.
thanks
Gaurav

2018-12-21 20:01 UTC, ericsysmin commented on python/avi/sdk/utils/api_utils.py
> +        if entity_type == 'controller':
@grastogi23 I think this may fix it it did fail this looks like it works however not sure if best way to do this

2018-12-21 20:03 UTC, ericsysmin commented on python/avi/sdk/utils/api_utils.py
> +        if entity_type == 'controller':
Updated, it did fail when I tested

2018-12-21 22:12 UTC, ericsysmin commented
@grastogi23 tested, works now, because there's no `entity_name` it was tossing an error. Once you make that an optional value, everything works well.

2018-12-22 20:15 UTC, grastogi23 approved these changes

2018-12-22 20:16 UTC, merged