AV-51788 Added cross tenant cloning service.
vmware/alb-sdk pull request #833
Opened 2019-01-03 15:42 UTC by gitshrikant

2019-01-04 06:17 UTC, chaitanyaavi commented on python/avi/migrationtools/f5_converter/f5_config_converter.py
>          LOG.debug('$$$$$$%s$$$$$$' % merge_object_mapping)
Delete this line or put a proper debug statement

2019-01-07 14:00 UTC, chaitanyaavi commented
Add progress bar and prorer debug messages for this class

2019-01-10 19:20 UTC, grastogi23 requested changes

2019-01-10 19:20 UTC, grastogi23 commented on python/avi/migrationtools/avi_migration_utils.py
> +        type = url.split('?')[0]
this should check for key error in case url does not have ?. we had seen cases like this in past.

2019-01-10 19:20 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/clone_cross_tenant_obj.py
> +    'VirtualService', 'L4PolicySet', 'VSDataScriptSet', 'HTTPPolicySet',
can we auto generate this list. I worry if new objects get added then we may miss those.

2019-01-10 19:20 UTC, grastogi23 commented on python/avi/migrationtools/f5_converter/clone_cross_tenant_obj.py
> +            return None, cloned_obj_ref
may be add debug line that would help when troubleshooting issues.

2019-01-15 13:21 UTC, gitshrikant commented on python/avi/migrationtools/avi_migration_utils.py
> +        type = url.split('?')[0]
Modified function to handle different URL formats.

2019-01-17 12:55 UTC, gitshrikant commented on python/avi/migrationtools/f5_converter/clone_cross_tenant_obj.py
> +    'VirtualService', 'L4PolicySet', 'VSDataScriptSet', 'HTTPPolicySet',
Auto-generated list of avi object types.

2019-01-17 17:21 UTC, grastogi23 approved these changes

2019-01-17 17:21 UTC, merged