AV-55613 AV-55707 AV-55706 AV-55704 saml sdk epic 18.2.2
vmware/alb-sdk pull request #849
Opened 2019-02-15 10:26 UTC by gitshrikant

1. Skeleton of SAML SDK for different IDPs:
-- There is one single class SAMLApiSession which is inherited from APISession class and The corresponding IDP class.
-- We need to provide 'idp' which is IDP type during SAMLApiSession initialization. eg. okta, onelogin, pingfed, etc
-- SAMLApiSession class in dynamically inherited from respective IDP Class as per the 'idp' input.
-- Each IDP class is extending base APISession class and override base class methods such as get_session, authentication methods.
-- To integrate other IDP, we can add it by creating a separate class and override get_session and authenticate methods for that corresponding IDP. Then add that entry into idp_class_factory function which returns class instance for given IDP type which intern is dynamically inherited for SAMLApiSession class as per the IDP type. Following is the example code to do SAML authentication and get the objects from the controller.

Eg.
`s = SAMLApiSession("controller_ip", username="foo",password="foo", idp="okta")
rsp = s.get('healthmonitor')
print rsp.text
rsp = s.get('pool')
print rsp.text
s.close()`

2019-02-20 05:35 UTC, grastogi23 reviewed
pl. review.

2019-02-20 05:35 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +                inactive_session = ApiSession.get_session(
why do we need to fetch session again?

2019-02-20 05:35 UTC, grastogi23 commented on python/avi/sdk/saml_avi_api.py
> +from avi.sdk.avi_api import *
bad practice of importing *

2019-02-20 05:38 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +            except Exception as e:
no error when sessio nis not found.

2019-02-20 09:58 UTC, gitshrikant commented on python/avi/sdk/saml_avi_api.py
> +from avi.sdk.avi_api import *
Removed import * and importing only required packages.

2019-02-21 06:49 UTC, gitshrikant commented on python/avi/sdk/avi_api.py
> +                inactive_session = ApiSession.get_session(
Refactorred code and using existing inactive session to call logout URI.

2019-02-21 06:50 UTC, gitshrikant commented on python/avi/sdk/avi_api.py
> +            except Exception as e:
Handled exception and pass this exception just by reporting warning "Session Not Found."

2019-02-21 06:58 UTC, gitshrikant reviewed
Abstraction of SAMLApiSession class is been implemented because to integrate this SAML SDK into the Ansible we will not need to mention specific IDP class while creating the session. Using this abstract class, a user just provides the IDP input and this class will take care of creating the specific IDP class object.

2019-02-22 16:27 UTC, grastogi23 requested changes
can you please cleanup the code and remove all the strs and redundant code. I am not convinced of all the error handling in the interactions during SAML assertions.

2019-02-22 16:27 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +                          max_api_retries=max_api_retries, idp=idp)
why do we need the idp class here.  The idpclass should have their own derived class implementations of the self.authenticate_session()

2019-02-22 16:27 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +                sessionDict[self.key]['session_id'],
why split in two lines?

2019-02-22 16:27 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +        idp_class = ApiSession
let the get_idp_class return ApiSession if idp is null.

2019-02-22 16:27 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +                max_api_retries=max_api_retries, idp=idp)
idp classes should remember the idp value. they should not take this parameter again.

2019-02-22 16:27 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +            logger.error("Provided IDP implementation not found.")
It should simply return ApiSession class for none case which is default.

2019-02-22 16:27 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +        if self.key in sessionDict and 'csrftoken' in \
I don't like unnecessary use of "\\". It makes the code ugly.

2019-02-22 16:27 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +            api_hdrs['X-CSRFToken'] = \
no need to change these lines.

2019-02-22 16:27 UTC, grastogi23 commented on python/avi/sdk/saml_avi_api.py
> +            raise StandardError(err)
why do we need to convert to the StandardError instead of simply using ApiError? this is change in the intervace.

2019-02-22 16:27 UTC, grastogi23 commented on python/avi/sdk/saml_avi_api.py
> +                err = APIError("Error No SAML response from IDP. "
can we be consistent on the ApiError vs standarderror.

2019-02-22 16:27 UTC, grastogi23 commented on python/avi/sdk/saml_avi_api.py
> +                        "sent to IDP with existing IDP cookies.")
we should print out the controller IP for which SAML is being set and may be the SAML url as well,.

2019-02-22 16:27 UTC, grastogi23 commented on python/avi/sdk/saml_avi_api.py
> +                             str(e.message))
no need to do str()

2019-02-22 16:27 UTC, grastogi23 commented on python/avi/sdk/saml_avi_api.py
> +                                            allow_redirects=False)
what if there are no exception and response is simply 401 or 5xx?

2019-02-25 08:31 UTC, gitshrikant commented on python/avi/sdk/avi_api.py
> +        if self.key in sessionDict and 'csrftoken' in \
I was following 80 characters pep8 standard. As this line exceeds 80 characters I need to split it.

2019-02-25 09:04 UTC, gitshrikant commented on python/avi/sdk/avi_api.py
> +                sessionDict[self.key]['session_id'],
Unnecessary split. Reverting this.

2019-02-25 09:05 UTC, gitshrikant commented on python/avi/sdk/avi_api.py
> +        idp_class = ApiSession
Changed get_idp_class to return ApiSession if idp is None.

2019-02-25 11:07 UTC, gitshrikant commented on python/avi/sdk/avi_api.py
> +                          max_api_retries=max_api_retries, idp=idp)
An IDP class has its own implementation of authenticate_session() method. IDP class just extends authenticate_session method from the base class AviSession. To override the base class's (AviSession) authenticate_method we required this initialization of idp_class in the AviSession class. This way self.authenticate_session method of Avisession class is overridden with the IDP class's authenticate_session method.

2019-02-25 12:18 UTC, gitshrikant commented on python/avi/sdk/saml_avi_api.py
> +                             str(e.message))
removed str()

2019-02-25 13:33 UTC, gitshrikant commented on python/avi/sdk/saml_avi_api.py
> +            raise StandardError(err)
Using ApiError instead of StandardError.

2019-02-25 13:34 UTC, gitshrikant commented on python/avi/sdk/saml_avi_api.py
> +                        "sent to IDP with existing IDP cookies.")
Printing SAML controller URL.

2019-02-25 13:34 UTC, gitshrikant commented on python/avi/sdk/saml_avi_api.py
> +                                            allow_redirects=False)
Added checks for response codes from IDP.

2019-02-25 13:39 UTC, gitshrikant commented on python/avi/sdk/avi_api.py
> +                max_api_retries=max_api_retries, idp=idp)
The idp parameter is we need to specify when calling the get_session static method. This method is called without class instance. How can the IDP class remember this?

2019-02-26 16:33 UTC, gitshrikant reviewed
@grastogi23 Travis is failing because of the coverage test. SAML tests are added and they can not be run on Travis. So, they are skipped and test coverage drop below 80% which is a threshold to pass minimum coverage required to pass the Travis. Should we set this threshold to 75% or is there any other way?

2019-03-05 02:19 UTC, grastogi23 requested changes

2019-03-05 02:19 UTC, grastogi23 commented on README.md
> +api = OktaSAMLApiSession.get_session("10.10.10.42", "okta_username", "okta_password")
If you are using factory then it should be 
ApiSession.get_session("10.10.10.42", "okta_username", "okta_password", idp=OktaSAMLApiSession)

If you are not then it should simply be
OktaSAMLApiSession("10.10.10.42", "okta_username", "okta_password")

2019-03-05 02:19 UTC, grastogi23 commented on README.md
> +api = OktaSAMLApiSession.get_session("10.10.10.42", "okta_username", "okta_password")
Please do the same for onelogin

2019-03-05 02:19 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +    def get_idp_class(idp):
why not just take the idp class as the input rather than converting it?

2019-03-05 02:19 UTC, grastogi23 commented on python/avi/sdk/saml_avi_api.py
> +    def __init__(self, controller=None, username=None, password=None,
it shouldn't need idp

2019-03-05 02:19 UTC, grastogi23 commented on python/avi/sdk/samples/virtualservice_examples_api.py
> +    # api = OktaSAMLApiSession(args.controller_ip, args.user, args.password,
why are these commented out?

2019-03-05 02:19 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +            idp_class = OneloginSAMLApiSession
I think we should let the caller pass the IDP class itself. This way it can be properly tested.

2019-03-05 05:18 UTC, gitshrikant commented on python/avi/sdk/avi_api.py
> +    def get_idp_class(idp):
I thought it is more easy for the user to pass string idp value i.e. 'okta' or 'onelogin' and we can hide the complexity of instantiating corresponding IDP class. This can be done other way around as you commented. Modifying this according to the comments.

2019-03-05 05:34 UTC, gitshrikant commented on python/avi/sdk/samples/virtualservice_examples_api.py
> +    # api = OktaSAMLApiSession(args.controller_ip, args.user, args.password,
These are commented out just to show how SAML based controller session can be initiated. Otherwise, I can create a separate example for SAML based authentication.

2019-03-05 05:35 UTC, gitshrikant commented on python/avi/sdk/samples/virtualservice_examples_api.py
> +    # api = OktaSAMLApiSession(args.controller_ip, args.user, args.password,
I will create seperate examl for SAML.

2019-03-05 06:11 UTC, gitshrikant commented on python/avi/sdk/avi_api.py
> +            idp_class = OneloginSAMLApiSession
Modified accordingly.

2019-03-05 06:28 UTC, gitshrikant commented on python/avi/sdk/saml_avi_api.py
> +    def __init__(self, controller=None, username=None, password=None,
removed idp.

2019-03-05 06:28 UTC, gitshrikant commented on README.md
> +api = OktaSAMLApiSession.get_session("10.10.10.42", "okta_username", "okta_password")
Done.

2019-03-05 16:10 UTC, grastogi23 requested changes

2019-03-05 16:10 UTC, grastogi23 commented on README.md
> +api = ApiSession.get_session("10.10.10.42", "onelogin_username", "onelogin_password", idp="OneloginSAMLApiSession")
change the example to pass the Class itself. OneloginSAMLApiSession

2019-03-05 16:10 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
>          :param retry_conxn_errors: retry on connection errors
Add documentation for idp. Ideally change idp to idp_class.

2019-03-05 16:10 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
>          :param retry_conxn_errors: retry on connection errors
documentation should say the two IDP supported. may be check for validity of them here. The base class type should be ApiSession.

2019-03-05 16:10 UTC, grastogi23 commented on python/avi/sdk/saml_avi_api.py
> +        self.idp_cookies = idp_cookies
There are no doc strings for the arguments.

2019-03-05 16:10 UTC, grastogi23 commented on python/avi/sdk/saml_avi_api.py
> +        :return: controller session and IDP response
add doc strings for username and password.

2019-03-05 16:10 UTC, grastogi23 commented on python/avi/sdk/saml_avi_api.py
> +        saml_response_regex = r'<input type=\"hidden\" ' \
These can be class variables. no need to create with every session.

2019-03-06 12:13 UTC, gitshrikant commented on README.md
> +api = ApiSession.get_session("10.10.10.42", "onelogin_username", "onelogin_password", idp="OneloginSAMLApiSession")
changed!

2019-03-08 09:58 UTC, closed without merging