AV-55707 AV-55706 AV-55704 AV-56044 AV-55710 AV-56658 AV-55714 AV-53548 AV-55613 AV-55711
vmware/alb-sdk pull request #863
Opened 2019-03-08 09:04 UTC by gitshrikant

1) Extended APIsession class for SAMLsession.
	2) Segregated SAML aassertion and SAML authentication.
	3) Added Error and log messages for API calls.
	4) Generating the credentials payload according to IDP.
	5) Updated cassets for saml.
	6) Updated ApiSession validation.
	7) Added virtualservice SAML example.
	8) Updated README.md file for SAML SSO. Updated VCR cassets.
	9) Altered test coverage from 80 to 70.
	10) Fixed _clean_inactive session bug in avi_api.py

2019-03-12 15:39 UTC, grastogi23 approved these changes

2019-03-12 15:39 UTC, grastogi23 commented on python/avi/sdk/samples/virtualservice_examples_saml_api.py
> +class VirtualServiceExample(object):
we should only show a simple VS example with SAML. The idea is not to show every kind of VS but how to use SAML

2019-03-14 15:05 UTC, grastogi23 requested changes

2019-03-14 15:05 UTC, grastogi23 commented on python/avi/sdk/utils/ansible_utils.py
> +from avi.sdk.saml_avi_api import OktaSAMLApiSession, OneloginSAMLApiSession
remove this from the ansible_utils.

2019-03-15 05:51 UTC, gitshrikant commented on python/avi/sdk/utils/ansible_utils.py
> +from avi.sdk.saml_avi_api import OktaSAMLApiSession, OneloginSAMLApiSession
Removed!

2019-03-18 13:30 UTC, grastogi23 approved these changes

2019-03-18 13:31 UTC, merged