Av 60483 logout session issue master
vmware/alb-sdk pull request #887
Opened 2019-04-11 13:20 UTC by gitshrikant

2019-04-11 14:50 UTC, grastogi23 requested changes

2019-04-11 14:50 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +            except (ConnectionError, KeyError, APIError) as e:
let us change it to Exception

2019-04-11 15:33 UTC, gitshrikant commented on python/avi/sdk/avi_api.py
> +            except (ConnectionError, KeyError, APIError) as e:
Added.

2019-04-11 16:02 UTC, grastogi23 approved these changes

2019-04-11 22:38 UTC, grastogi23 approved these changes

2019-04-15 01:18 UTC, grastogi23 approved these changes

2019-04-15 01:18 UTC, merged