Updated go clients for Delete and Get Object from tenant
vmware/alb-sdk pull request #936
Opened 2019-06-13 16:33 UTC by Rohan-sss1

2019-06-13 16:41 UTC, Rohan-sss1 commented
Hi @grastogi23 I have Updated the go clients as per our new functions and also tested the avisession_test.go all tests are passing. 

=== RUN   TestAviSession
--- PASS: TestAviSession (12.82s)
=== RUN   TestAviPool
--- PASS: TestAviPool (5.11s)
=== RUN   TestTenantSwitch
--- PASS: TestTenantSwitch (3.97s)
=== RUN   TestAviDefaultFields
--- PASS: TestAviDefaultFields (5.40s)
=== RUN   TestTokenAuthRobustness
--- SKIP: TestTokenAuthRobustness (0.00s)
   avisession_test.go:296: SKIPPING as test not running in controller.
=== RUN   TestAviReads
--- PASS: TestAviReads (8.14s)
PASS
ok      github.com/avinetworks/sdk/go/session    35.445s

2019-06-14 05:07 UTC, grastogi23 requested changes

2019-06-14 05:07 UTC, grastogi23 commented on go/session/avisession.go
> +func (avisess *AviSession) restRequestWithOptions(verb string, uri string, payload interface{}, tenant string, retryNum ...int) ([]byte, error) {
Let us make the restRequest call restRequestWithOptions. This way there is a single implementation. 

Also, add the version as a parameter as well. If version is nil then use avisess.version.

2019-06-14 05:07 UTC, grastogi23 commented on go/session/avisession.go
> +	req.Header.Set("X-Avi-Tenant", tenant)
tenant should be checked if nil use avisess.tenant.

2019-06-14 05:07 UTC, grastogi23 commented on go/session/avisession.go
> +	req, errorResult := avisess.newAviRequest(verb, url, payloadIO)
tenant should be passed here were it was previously being handled.

2019-06-14 05:07 UTC, grastogi23 commented on go/session/avisession.go
> +	req.Header.Set("Accept", "application/json")
in fact move this line inside the newAviRequest.

2019-06-14 05:07 UTC, grastogi23 commented on go/session/avisession.go
> +	if opts.tenant != "" {
this code will get simplified once restRequestWithOptions is merged with restRequest.

2019-06-14 05:07 UTC, grastogi23 commented on go/session/avisession.go
> +	opts.tenant = tenant
check for nil condition.

2019-06-14 05:07 UTC, grastogi23 commented on go/session/avisession_test.go
> +	err = avisess.GetObject("pool", SetName("test-admin-pool"),SetOptTenant("Test-Admin"), SetResult(&npool2))
the code is not go fmt... like spacings are all bad.

2019-06-14 05:07 UTC, grastogi23 commented on go/session/avisession_test.go
> +}
no new line

2019-06-14 05:07 UTC, grastogi23 commented on go/clients/actiongroupconfig_client.go
> +		return client.aviSession.DeleteObject(client.getAPIPath(uuid), options...)
can this delete simply not pass the options down to the DeleteObject. 
If we are changing the delete we should also change all the other methods too like Get, Put, Post etc.

2019-06-14 10:19 UTC, Rohan-sss1 commented on go/session/avisession.go
> +func (avisess *AviSession) restRequestWithOptions(verb string, uri string, payload interface{}, tenant string, retryNum ...int) ([]byte, error) {
Instead of calling restRequestWithOptions from restRequest we can add more parameters in restRequest function as tenant or more. because in restRequestWithOptions function we only updating the header and the flow is the same as restRequest function. we can also pass parameters as empty value and from the empty value function will work for admin tenant otherwise it will work from the tenant which we are passing to the function

2019-06-19 04:52 UTC, grastogi23 requested changes
a few more changes.

2019-06-19 04:54 UTC, grastogi23 commented
update the PR to the master.

2019-06-19 10:11 UTC, Rohan-sss1 commented on go/session/avisession_test.go
> +	err = avisess.GetObject("pool", SetName("test-admin-pool"),SetOptTenant("Test-Admin"), SetResult(&npool2))
Resolved

2019-06-19 10:16 UTC, Rohan-sss1 commented on go/session/avisession_test.go
> +}
Resolved

2019-06-19 10:23 UTC, Rohan-sss1 commented on go/session/avisession.go
> +	req.Header.Set("Accept", "application/json")
Resolved

2019-06-19 10:23 UTC, Rohan-sss1 commented on go/session/avisession.go
> +	opts.tenant = tenant
We can not check nil for string type

2019-06-19 14:41 UTC, grastogi23 approved these changes

2019-06-19 14:43 UTC, merged