Add method to do get_all operaion
vmware/alb-sdk pull request #955
Opened 2019-07-24 13:17 UTC by sandeepavi

2019-07-24 13:19 UTC, sandeepavi commented on python/avi/sdk/avi_api.py
> +        for obj in all_objs:
@grastogi23  I am not sure what benefit we get by using this generator model as we anyways have all the objects in memory.

We could do a simple `return all_objs` .
Please let me know your thoughts.

2019-07-25 15:49 UTC, grastogi23 requested changes
please see inline comments.

2019-07-25 15:49 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +        for obj in all_objs:
we should not keep all objects in the memory... The semantics is to provide an iterator not fetch all objects.

2019-07-25 15:49 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +                                timeout=None, params=None, api_version=None,
should document the parameters. Also provide an example use of this api.

let us call it get_objects_iter so it is explicit that it is not return all objects but an iterator to iterate over objects.

2019-07-25 15:51 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +        params['page_size'] = 200 # Max limt on Controller
let us take the page_size from the params as well. But, we can check for max of 200

2019-07-25 15:51 UTC, grastogi23 commented on python/avi/sdk/avi_api.py
> +                            params=params, api_version=api_version, **kwargs).json()
what happens in case of error. It should raise exception?

2019-07-30 11:07 UTC, sandeepavi commented on python/avi/sdk/avi_api.py
> +        resp = self.get(*args, **kwargs).json()
.json() method in avi_api.py checks and raises various exceptions. Hence left the exception handling as it is already taken care of json() method @ https://github.com/avinetworks/sdk/blob/bba674f45ce80374f2491a24b2137050cf86f70a/python/avi/sdk/avi_api.py#L89

2019-08-07 09:36 UTC, grastogi23 approved these changes

2019-08-20 09:32 UTC, chaitanyaavi approved these changes

2019-08-20 16:35 UTC, grastogi23 approved these changes

2019-08-20 16:35 UTC, merged